/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq;


import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.*;
import ua.ddovgal.brainshareApi.jooq.tables.records.*;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>brainshare_dev</code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RCommentaryRecord, ULong> IDENTITY_COMMENTARY = Identities0.IDENTITY_COMMENTARY;
    public static final Identity<RContentDataRecord, ULong> IDENTITY_CONTENT_DATA = Identities0.IDENTITY_CONTENT_DATA;
    public static final Identity<RCourseRecord, ULong> IDENTITY_COURSE = Identities0.IDENTITY_COURSE;
    public static final Identity<RGenericNotificationRecord, ULong> IDENTITY_GENERIC_NOTIFICATION = Identities0.IDENTITY_GENERIC_NOTIFICATION;
    public static final Identity<RInCommentaryModeratorRequestRecord, ULong> IDENTITY_IN_COMMENTARY_MODERATOR_REQUEST = Identities0.IDENTITY_IN_COMMENTARY_MODERATOR_REQUEST;
    public static final Identity<RMaterialRecord, ULong> IDENTITY_MATERIAL = Identities0.IDENTITY_MATERIAL;
    public static final Identity<RModificationRecord, ULong> IDENTITY_MODIFICATION = Identities0.IDENTITY_MODIFICATION;
    public static final Identity<RObjectStorageFileRecord, ULong> IDENTITY_OBJECT_STORAGE_FILE = Identities0.IDENTITY_OBJECT_STORAGE_FILE;
    public static final Identity<RSectionRecord, UInteger> IDENTITY_SECTION = Identities0.IDENTITY_SECTION;
    public static final Identity<RUserRecord, ULong> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RCommentaryRecord> KEY_COMMENTARY_PRIMARY = UniqueKeys0.KEY_COMMENTARY_PRIMARY;
    public static final UniqueKey<RCommentaryRecord> KEY_COMMENTARY_CONTENT_DATA_UNIQUE = UniqueKeys0.KEY_COMMENTARY_CONTENT_DATA_UNIQUE;
    public static final UniqueKey<RCommentaryMarkRecord> KEY_COMMENTARY_MARK_PRIMARY = UniqueKeys0.KEY_COMMENTARY_MARK_PRIMARY;
    public static final UniqueKey<RContentDataRecord> KEY_CONTENT_DATA_PRIMARY = UniqueKeys0.KEY_CONTENT_DATA_PRIMARY;
    public static final UniqueKey<RCourseRecord> KEY_COURSE_PRIMARY = UniqueKeys0.KEY_COURSE_PRIMARY;
    public static final UniqueKey<RGenericNotificationRecord> KEY_GENERIC_NOTIFICATION_PRIMARY = UniqueKeys0.KEY_GENERIC_NOTIFICATION_PRIMARY;
    public static final UniqueKey<RInCommentaryModeratorRequestRecord> KEY_IN_COMMENTARY_MODERATOR_REQUEST_PRIMARY = UniqueKeys0.KEY_IN_COMMENTARY_MODERATOR_REQUEST_PRIMARY;
    public static final UniqueKey<RMaterialRecord> KEY_MATERIAL_PRIMARY = UniqueKeys0.KEY_MATERIAL_PRIMARY;
    public static final UniqueKey<RMaterialRecord> KEY_MATERIAL_CONTENT_DATA_UNIQUE = UniqueKeys0.KEY_MATERIAL_CONTENT_DATA_UNIQUE;
    public static final UniqueKey<RMaterialAttachmentRecord> KEY_MATERIAL_ATTACHMENT_PRIMARY = UniqueKeys0.KEY_MATERIAL_ATTACHMENT_PRIMARY;
    public static final UniqueKey<RMaterialFormatRecord> KEY_MATERIAL_FORMAT_PRIMARY = UniqueKeys0.KEY_MATERIAL_FORMAT_PRIMARY;
    public static final UniqueKey<RMaterialFormatRecord> KEY_MATERIAL_FORMAT_FORMAT_NAME_UNIQUE = UniqueKeys0.KEY_MATERIAL_FORMAT_FORMAT_NAME_UNIQUE;
    public static final UniqueKey<RMaterialMarkRecord> KEY_MATERIAL_MARK_PRIMARY = UniqueKeys0.KEY_MATERIAL_MARK_PRIMARY;
    public static final UniqueKey<RMaterialRecommendationRecord> KEY_MATERIAL_RECOMMENDATION_PRIMARY = UniqueKeys0.KEY_MATERIAL_RECOMMENDATION_PRIMARY;
    public static final UniqueKey<RMaterialStateRecord> KEY_MATERIAL_STATE_PRIMARY = UniqueKeys0.KEY_MATERIAL_STATE_PRIMARY;
    public static final UniqueKey<RMaterialStateRecord> KEY_MATERIAL_STATE_STATE_UNIQUE = UniqueKeys0.KEY_MATERIAL_STATE_STATE_UNIQUE;
    public static final UniqueKey<RMaterialViewRecord> KEY_MATERIAL_VIEW_PRIMARY = UniqueKeys0.KEY_MATERIAL_VIEW_PRIMARY;
    public static final UniqueKey<RModificationRecord> KEY_MODIFICATION_PRIMARY = UniqueKeys0.KEY_MODIFICATION_PRIMARY;
    public static final UniqueKey<RNotificationAboutMaterialAchievementRecord> KEY_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_PRIMARY;
    public static final UniqueKey<RNotificationAboutNewMaterialRecord> KEY_NOTIFICATION_ABOUT_NEW_MATERIAL_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_ABOUT_NEW_MATERIAL_PRIMARY;
    public static final UniqueKey<RNotificationAboutNewModificationRecord> KEY_NOTIFICATION_ABOUT_NEW_MODIFICATION_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_ABOUT_NEW_MODIFICATION_PRIMARY;
    public static final UniqueKey<RNotificationAboutSubcommentRecord> KEY_NOTIFICATION_ABOUT_SUBCOMMENT_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_ABOUT_SUBCOMMENT_PRIMARY;
    public static final UniqueKey<RNotificationTypeRecord> KEY_NOTIFICATION_TYPE_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_TYPE_PRIMARY;
    public static final UniqueKey<RNotificationWithoutReasonReferenceRecord> KEY_NOTIFICATION_WITHOUT_REASON_REFERENCE_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_WITHOUT_REASON_REFERENCE_PRIMARY;
    public static final UniqueKey<RObjectStorageFileRecord> KEY_OBJECT_STORAGE_FILE_PRIMARY = UniqueKeys0.KEY_OBJECT_STORAGE_FILE_PRIMARY;
    public static final UniqueKey<RSectionRecord> KEY_SECTION_PRIMARY = UniqueKeys0.KEY_SECTION_PRIMARY;
    public static final UniqueKey<RSubscriptionRecord> KEY_SUBSCRIPTION_ALL_COLUMN_UNIQUE = UniqueKeys0.KEY_SUBSCRIPTION_ALL_COLUMN_UNIQUE;
    public static final UniqueKey<RUserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<RUserRecord> KEY_USER_AVATAR_UNIQUE = UniqueKeys0.KEY_USER_AVATAR_UNIQUE;
    public static final UniqueKey<RUserRecord> KEY_USER_EMAIL_UNIQUE = UniqueKeys0.KEY_USER_EMAIL_UNIQUE;
    public static final UniqueKey<RUserRecord> KEY_USER_LOGIN_UNIQUE = UniqueKeys0.KEY_USER_LOGIN_UNIQUE;
    public static final UniqueKey<RUserBookmarkRecord> KEY_USER_BOOKMARK_PRIMARY = UniqueKeys0.KEY_USER_BOOKMARK_PRIMARY;
    public static final UniqueKey<RUserDeferredMaterialRecord> KEY_USER_DEFERRED_MATERIAL_PRIMARY = UniqueKeys0.KEY_USER_DEFERRED_MATERIAL_PRIMARY;
    public static final UniqueKey<RUserDesirableSectionRecord> KEY_USER_DESIRABLE_SECTION_PRIMARY = UniqueKeys0.KEY_USER_DESIRABLE_SECTION_PRIMARY;
    public static final UniqueKey<RUserFavouriteMaterialRecord> KEY_USER_FAVOURITE_MATERIAL_PRIMARY = UniqueKeys0.KEY_USER_FAVOURITE_MATERIAL_PRIMARY;
    public static final UniqueKey<RUserSavedAttachmentRecord> KEY_USER_SAVED_ATTACHMENT_PRIMARY = UniqueKeys0.KEY_USER_SAVED_ATTACHMENT_PRIMARY;
    public static final UniqueKey<RUserStatusRecord> KEY_USER_STATUS_PRIMARY = UniqueKeys0.KEY_USER_STATUS_PRIMARY;
    public static final UniqueKey<RUserStatusRecord> KEY_USER_STATUS_STATUS_NAME_UNIQUE = UniqueKeys0.KEY_USER_STATUS_STATUS_NAME_UNIQUE;
    public static final UniqueKey<RUserStatusInSectionRecord> KEY_USER_STATUS_IN_SECTION_PRIMARY = UniqueKeys0.KEY_USER_STATUS_IN_SECTION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RCommentaryRecord, RUserRecord> FK_COMMENTARY_AUTHOR_USER_ID = ForeignKeys0.FK_COMMENTARY_AUTHOR_USER_ID;
    public static final ForeignKey<RCommentaryRecord, RMaterialRecord> FK_COMMENTARY_MATERIAL_ID = ForeignKeys0.FK_COMMENTARY_MATERIAL_ID;
    public static final ForeignKey<RCommentaryRecord, RCommentaryRecord> FK_COMMENTARY_POSSIBLE_PARENT_COMMENTARY_ID = ForeignKeys0.FK_COMMENTARY_POSSIBLE_PARENT_COMMENTARY_ID;
    public static final ForeignKey<RCommentaryRecord, RContentDataRecord> FK_COMMENTARY_COMMENTARY_CONTENT_DATA = ForeignKeys0.FK_COMMENTARY_COMMENTARY_CONTENT_DATA;
    public static final ForeignKey<RCommentaryMarkRecord, RCommentaryRecord> FK_COMMENTARY_MARK_COMMENTARY_ID = ForeignKeys0.FK_COMMENTARY_MARK_COMMENTARY_ID;
    public static final ForeignKey<RCommentaryMarkRecord, RUserRecord> FK_COMMENTARY_MARK_SETTER_USER_ID = ForeignKeys0.FK_COMMENTARY_MARK_SETTER_USER_ID;
    public static final ForeignKey<RCourseRecord, RUserRecord> FK_COURSE_CREATOR_USER_ID = ForeignKeys0.FK_COURSE_CREATOR_USER_ID;
    public static final ForeignKey<RCourseRecord, RSectionRecord> FK_COURSE_SECTION_ID = ForeignKeys0.FK_COURSE_SECTION_ID;
    public static final ForeignKey<RGenericNotificationRecord, RUserRecord> FK_GENERIC_NOTIFICATION_RECEIVER_USER_ID = ForeignKeys0.FK_GENERIC_NOTIFICATION_RECEIVER_USER_ID;
    public static final ForeignKey<RGenericNotificationRecord, RNotificationTypeRecord> FK_GENERIC_NOTIFICATION_TYPE_ID = ForeignKeys0.FK_GENERIC_NOTIFICATION_TYPE_ID;
    public static final ForeignKey<RInCommentaryModeratorRequestRecord, RCommentaryRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_COMMENTARY_ID = ForeignKeys0.FK_IN_COMMENTARY_MODERATOR_REQUEST_COMMENTARY_ID;
    public static final ForeignKey<RInCommentaryModeratorRequestRecord, RMaterialRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_MATERIAL_ID = ForeignKeys0.FK_IN_COMMENTARY_MODERATOR_REQUEST_MATERIAL_ID;
    public static final ForeignKey<RInCommentaryModeratorRequestRecord, RSectionRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_SECTION_OF_MATERIAL_ID = ForeignKeys0.FK_IN_COMMENTARY_MODERATOR_REQUEST_SECTION_OF_MATERIAL_ID;
    public static final ForeignKey<RMaterialRecord, RUserRecord> FK_MATERIAL_AUTHOR_USER_ID = ForeignKeys0.FK_MATERIAL_AUTHOR_USER_ID;
    public static final ForeignKey<RMaterialRecord, RMaterialStateRecord> FK_MATERIAL_STATE_ID = ForeignKeys0.FK_MATERIAL_STATE_ID;
    public static final ForeignKey<RMaterialRecord, RMaterialFormatRecord> FK_MATERIAL_FORMAT_ID = ForeignKeys0.FK_MATERIAL_FORMAT_ID;
    public static final ForeignKey<RMaterialRecord, RCourseRecord> FK_MATERIAL_POSSIBLE_COURSE_ID = ForeignKeys0.FK_MATERIAL_POSSIBLE_COURSE_ID;
    public static final ForeignKey<RMaterialRecord, RSectionRecord> FK_MATERIAL_MATERIAL_SECTION_ID = ForeignKeys0.FK_MATERIAL_MATERIAL_SECTION_ID;
    public static final ForeignKey<RMaterialRecord, RContentDataRecord> FK_MATERIAL_MATERIAL_CONTENT_DATA_ID = ForeignKeys0.FK_MATERIAL_MATERIAL_CONTENT_DATA_ID;
    public static final ForeignKey<RMaterialAttachmentRecord, RMaterialRecord> FK_MATERIAL_ATTACHMENT_MATERIAL_ID = ForeignKeys0.FK_MATERIAL_ATTACHMENT_MATERIAL_ID;
    public static final ForeignKey<RMaterialAttachmentRecord, RObjectStorageFileRecord> FK_MATERIAL_ATTACHMENT_OBJECT_STORAGE_FILE_ID = ForeignKeys0.FK_MATERIAL_ATTACHMENT_OBJECT_STORAGE_FILE_ID;
    public static final ForeignKey<RMaterialMarkRecord, RMaterialRecord> FK_MATERIAL_MARK_MATERIAL_ID = ForeignKeys0.FK_MATERIAL_MARK_MATERIAL_ID;
    public static final ForeignKey<RMaterialMarkRecord, RUserRecord> FK_MATERIAL_MARK_SETTER_USER_ID = ForeignKeys0.FK_MATERIAL_MARK_SETTER_USER_ID;
    public static final ForeignKey<RMaterialRecommendationRecord, RMaterialRecord> FK_MATERIAL_RECOMMENDATION_SOURCE_MATERIAL_ID = ForeignKeys0.FK_MATERIAL_RECOMMENDATION_SOURCE_MATERIAL_ID;
    public static final ForeignKey<RMaterialRecommendationRecord, RMaterialRecord> FK_MATERIAL_RECOMMENDATION_RECOMMENDED_MATERIAL_ID = ForeignKeys0.FK_MATERIAL_RECOMMENDATION_RECOMMENDED_MATERIAL_ID;
    public static final ForeignKey<RMaterialViewRecord, RUserRecord> FK_MATERIAL_VIEW_VIEWER_USER_ID = ForeignKeys0.FK_MATERIAL_VIEW_VIEWER_USER_ID;
    public static final ForeignKey<RMaterialViewRecord, RMaterialRecord> FK_MATERIAL_VIEW_MATERIAL_ID = ForeignKeys0.FK_MATERIAL_VIEW_MATERIAL_ID;
    public static final ForeignKey<RModificationRecord, RMaterialRecord> FK_MODIFICATION_SOURCE_MATERIAL_ID = ForeignKeys0.FK_MODIFICATION_SOURCE_MATERIAL_ID;
    public static final ForeignKey<RModificationRecord, RUserRecord> FK_MODIFICATION_REQUESTER_USER_ID = ForeignKeys0.FK_MODIFICATION_REQUESTER_USER_ID;
    public static final ForeignKey<RNotificationAboutMaterialAchievementRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_NOTIFICATION_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_NOTIFICATION_ID;
    public static final ForeignKey<RNotificationAboutMaterialAchievementRecord, RMaterialRecord> FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_REASON_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_REASON_ID;
    public static final ForeignKey<RNotificationAboutNewMaterialRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_NEW_MATERIAL_NOTIFICATION_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_NEW_MATERIAL_NOTIFICATION_ID;
    public static final ForeignKey<RNotificationAboutNewMaterialRecord, RMaterialRecord> FK_NOTIFICATION_ABOUT_NEW_MATERIAL_REASON_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_NEW_MATERIAL_REASON_ID;
    public static final ForeignKey<RNotificationAboutNewModificationRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_NOTIFICATION_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_NOTIFICATION_ID;
    public static final ForeignKey<RNotificationAboutNewModificationRecord, RModificationRecord> FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_REASON_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_REASON_ID;
    public static final ForeignKey<RNotificationAboutSubcommentRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_SUBCOMMENT_NOTIFICATION_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_SUBCOMMENT_NOTIFICATION_ID;
    public static final ForeignKey<RNotificationAboutSubcommentRecord, RCommentaryRecord> FK_NOTIFICATION_ABOUT_SUBCOMMENT_REASON_ID = ForeignKeys0.FK_NOTIFICATION_ABOUT_SUBCOMMENT_REASON_ID;
    public static final ForeignKey<RNotificationWithoutReasonReferenceRecord, RGenericNotificationRecord> FK_NOTIFICATION_WITHOUT_REASON_REFERENCE_NOTIFICATION_ID = ForeignKeys0.FK_NOTIFICATION_WITHOUT_REASON_REFERENCE_NOTIFICATION_ID;
    public static final ForeignKey<RSectionRecord, RSectionRecord> FK_SECTION_POSSIBLE_SUPER_SECTION_ID = ForeignKeys0.FK_SECTION_POSSIBLE_SUPER_SECTION_ID;
    public static final ForeignKey<RSubscriptionRecord, RUserRecord> FK_SUBSCRIPTION_SUBSCRIBER_ID = ForeignKeys0.FK_SUBSCRIPTION_SUBSCRIBER_ID;
    public static final ForeignKey<RSubscriptionRecord, RUserRecord> FK_SUBSCRIPTION_AUTHORITY_ID = ForeignKeys0.FK_SUBSCRIPTION_AUTHORITY_ID;
    public static final ForeignKey<RUserRecord, RObjectStorageFileRecord> FK_USER_AVATAR_ID = ForeignKeys0.FK_USER_AVATAR_ID;
    public static final ForeignKey<RUserRecord, RUserStatusRecord> FK_USER_STATUS_ID = ForeignKeys0.FK_USER_STATUS_ID;
    public static final ForeignKey<RUserBookmarkRecord, RUserRecord> FK_USER_BOOKMARK_USER_ID = ForeignKeys0.FK_USER_BOOKMARK_USER_ID;
    public static final ForeignKey<RUserBookmarkRecord, RMaterialRecord> FK_USER_BOOKMARK_MATERIAL_ID = ForeignKeys0.FK_USER_BOOKMARK_MATERIAL_ID;
    public static final ForeignKey<RUserBookmarkRecord, RCourseRecord> FK_USER_BOOKMARK_POSSIBLE_COURSE_ID = ForeignKeys0.FK_USER_BOOKMARK_POSSIBLE_COURSE_ID;
    public static final ForeignKey<RUserDeferredMaterialRecord, RUserRecord> FK_USER_DEFERRED_MATERIAL_USER_ID = ForeignKeys0.FK_USER_DEFERRED_MATERIAL_USER_ID;
    public static final ForeignKey<RUserDeferredMaterialRecord, RMaterialRecord> FK_USER_DEFERRED_MATERIAL_MATERIAL_ID = ForeignKeys0.FK_USER_DEFERRED_MATERIAL_MATERIAL_ID;
    public static final ForeignKey<RUserDeferredMaterialRecord, RCourseRecord> FK_USER_DEFERRED_MATERIAL_POSSIBLE_COURSE_ID = ForeignKeys0.FK_USER_DEFERRED_MATERIAL_POSSIBLE_COURSE_ID;
    public static final ForeignKey<RUserDesirableSectionRecord, RUserRecord> FK_USER_DESIRABLE_SECTION_USER_ID = ForeignKeys0.FK_USER_DESIRABLE_SECTION_USER_ID;
    public static final ForeignKey<RUserDesirableSectionRecord, RSectionRecord> FK_USER_DESIRABLE_SECTION_SECTION_ID = ForeignKeys0.FK_USER_DESIRABLE_SECTION_SECTION_ID;
    public static final ForeignKey<RUserFavouriteMaterialRecord, RUserRecord> FK_USER_FAVOURITE_MATERIAL_USER_ID = ForeignKeys0.FK_USER_FAVOURITE_MATERIAL_USER_ID;
    public static final ForeignKey<RUserFavouriteMaterialRecord, RMaterialRecord> FK_USER_FAVOURITE_MATERIAL_MATERIAL_ID = ForeignKeys0.FK_USER_FAVOURITE_MATERIAL_MATERIAL_ID;
    public static final ForeignKey<RUserFavouriteMaterialRecord, RCourseRecord> FK_USER_FAVOURITE_MATERIAL_POSSIBLE_COURSE_ID = ForeignKeys0.FK_USER_FAVOURITE_MATERIAL_POSSIBLE_COURSE_ID;
    public static final ForeignKey<RUserSavedAttachmentRecord, RUserRecord> FK_USER_SAVED_ATTACHMENT_USER_ID = ForeignKeys0.FK_USER_SAVED_ATTACHMENT_USER_ID;
    public static final ForeignKey<RUserSavedAttachmentRecord, RMaterialAttachmentRecord> FK_USER_SAVED_ATTACHMENT_ATTACHMENT_ID = ForeignKeys0.FK_USER_SAVED_ATTACHMENT_ATTACHMENT_ID;
    public static final ForeignKey<RUserStatusInSectionRecord, RUserRecord> FK_USER_STATUS_IN_SECTION_USER_ID = ForeignKeys0.FK_USER_STATUS_IN_SECTION_USER_ID;
    public static final ForeignKey<RUserStatusInSectionRecord, RSectionRecord> FK_USER_STATUS_IN_SECTION_SECTION_ID = ForeignKeys0.FK_USER_STATUS_IN_SECTION_SECTION_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RCommentaryRecord, ULong> IDENTITY_COMMENTARY = createIdentity(TCommentary.COMMENTARY, TCommentary.COMMENTARY.ID);
        public static Identity<RContentDataRecord, ULong> IDENTITY_CONTENT_DATA = createIdentity(TContentData.CONTENT_DATA, TContentData.CONTENT_DATA.ID);
        public static Identity<RCourseRecord, ULong> IDENTITY_COURSE = createIdentity(TCourse.COURSE, TCourse.COURSE.ID);
        public static Identity<RGenericNotificationRecord, ULong> IDENTITY_GENERIC_NOTIFICATION = createIdentity(TGenericNotification.GENERIC_NOTIFICATION, TGenericNotification.GENERIC_NOTIFICATION.ID);
        public static Identity<RInCommentaryModeratorRequestRecord, ULong> IDENTITY_IN_COMMENTARY_MODERATOR_REQUEST = createIdentity(TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST, TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST.ID);
        public static Identity<RMaterialRecord, ULong> IDENTITY_MATERIAL = createIdentity(TMaterial.MATERIAL, TMaterial.MATERIAL.ID);
        public static Identity<RModificationRecord, ULong> IDENTITY_MODIFICATION = createIdentity(TModification.MODIFICATION, TModification.MODIFICATION.ID);
        public static Identity<RObjectStorageFileRecord, ULong> IDENTITY_OBJECT_STORAGE_FILE = createIdentity(TObjectStorageFile.OBJECT_STORAGE_FILE, TObjectStorageFile.OBJECT_STORAGE_FILE.ID);
        public static Identity<RSectionRecord, UInteger> IDENTITY_SECTION = createIdentity(TSection.SECTION, TSection.SECTION.ID);
        public static Identity<RUserRecord, ULong> IDENTITY_USER = createIdentity(TUser.USER, TUser.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RCommentaryRecord> KEY_COMMENTARY_PRIMARY = createUniqueKey(TCommentary.COMMENTARY, "KEY_commentary_PRIMARY", TCommentary.COMMENTARY.ID);
        public static final UniqueKey<RCommentaryRecord> KEY_COMMENTARY_CONTENT_DATA_UNIQUE = createUniqueKey(TCommentary.COMMENTARY, "KEY_commentary_content_data_UNIQUE", TCommentary.COMMENTARY.CONTENT_DATA_ID);
        public static final UniqueKey<RCommentaryMarkRecord> KEY_COMMENTARY_MARK_PRIMARY = createUniqueKey(TCommentaryMark.COMMENTARY_MARK, "KEY_commentary_mark_PRIMARY", TCommentaryMark.COMMENTARY_MARK.COMMENTARY_ID, TCommentaryMark.COMMENTARY_MARK.SETTER_USER_ID);
        public static final UniqueKey<RContentDataRecord> KEY_CONTENT_DATA_PRIMARY = createUniqueKey(TContentData.CONTENT_DATA, "KEY_content_data_PRIMARY", TContentData.CONTENT_DATA.ID);
        public static final UniqueKey<RCourseRecord> KEY_COURSE_PRIMARY = createUniqueKey(TCourse.COURSE, "KEY_course_PRIMARY", TCourse.COURSE.ID);
        public static final UniqueKey<RGenericNotificationRecord> KEY_GENERIC_NOTIFICATION_PRIMARY = createUniqueKey(TGenericNotification.GENERIC_NOTIFICATION, "KEY_generic_notification_PRIMARY", TGenericNotification.GENERIC_NOTIFICATION.ID);
        public static final UniqueKey<RInCommentaryModeratorRequestRecord> KEY_IN_COMMENTARY_MODERATOR_REQUEST_PRIMARY = createUniqueKey(TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST, "KEY_in_commentary_moderator_request_PRIMARY", TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST.ID);
        public static final UniqueKey<RMaterialRecord> KEY_MATERIAL_PRIMARY = createUniqueKey(TMaterial.MATERIAL, "KEY_material_PRIMARY", TMaterial.MATERIAL.ID);
        public static final UniqueKey<RMaterialRecord> KEY_MATERIAL_CONTENT_DATA_UNIQUE = createUniqueKey(TMaterial.MATERIAL, "KEY_material_content_data_UNIQUE", TMaterial.MATERIAL.CONTENT_DATA_ID);
        public static final UniqueKey<RMaterialAttachmentRecord> KEY_MATERIAL_ATTACHMENT_PRIMARY = createUniqueKey(TMaterialAttachment.MATERIAL_ATTACHMENT, "KEY_material_attachment_PRIMARY", TMaterialAttachment.MATERIAL_ATTACHMENT.OBJECT_STORAGE_FILE_ID);
        public static final UniqueKey<RMaterialFormatRecord> KEY_MATERIAL_FORMAT_PRIMARY = createUniqueKey(TMaterialFormat.MATERIAL_FORMAT, "KEY_material_format_PRIMARY", TMaterialFormat.MATERIAL_FORMAT.ID);
        public static final UniqueKey<RMaterialFormatRecord> KEY_MATERIAL_FORMAT_FORMAT_NAME_UNIQUE = createUniqueKey(TMaterialFormat.MATERIAL_FORMAT, "KEY_material_format_format_name_UNIQUE", TMaterialFormat.MATERIAL_FORMAT.FORMAT_NAME);
        public static final UniqueKey<RMaterialMarkRecord> KEY_MATERIAL_MARK_PRIMARY = createUniqueKey(TMaterialMark.MATERIAL_MARK, "KEY_material_mark_PRIMARY", TMaterialMark.MATERIAL_MARK.MATERIAL_ID, TMaterialMark.MATERIAL_MARK.SETTER_USER_ID);
        public static final UniqueKey<RMaterialRecommendationRecord> KEY_MATERIAL_RECOMMENDATION_PRIMARY = createUniqueKey(TMaterialRecommendation.MATERIAL_RECOMMENDATION, "KEY_material_recommendation_PRIMARY", TMaterialRecommendation.MATERIAL_RECOMMENDATION.SOURCE_MATERIAL_ID, TMaterialRecommendation.MATERIAL_RECOMMENDATION.RECOMMENDED_MATERIAL_ID);
        public static final UniqueKey<RMaterialStateRecord> KEY_MATERIAL_STATE_PRIMARY = createUniqueKey(TMaterialState.MATERIAL_STATE, "KEY_material_state_PRIMARY", TMaterialState.MATERIAL_STATE.ID);
        public static final UniqueKey<RMaterialStateRecord> KEY_MATERIAL_STATE_STATE_UNIQUE = createUniqueKey(TMaterialState.MATERIAL_STATE, "KEY_material_state_state_UNIQUE", TMaterialState.MATERIAL_STATE.STATE_NAME);
        public static final UniqueKey<RMaterialViewRecord> KEY_MATERIAL_VIEW_PRIMARY = createUniqueKey(TMaterialView.MATERIAL_VIEW, "KEY_material_view_PRIMARY", TMaterialView.MATERIAL_VIEW.VIEWER_USER_ID, TMaterialView.MATERIAL_VIEW.MATERIAL_ID);
        public static final UniqueKey<RModificationRecord> KEY_MODIFICATION_PRIMARY = createUniqueKey(TModification.MODIFICATION, "KEY_modification_PRIMARY", TModification.MODIFICATION.ID);
        public static final UniqueKey<RNotificationAboutMaterialAchievementRecord> KEY_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_PRIMARY = createUniqueKey(TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT, "KEY_notification_about_material_achievement_PRIMARY", TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT.NOTIFICATION_ID);
        public static final UniqueKey<RNotificationAboutNewMaterialRecord> KEY_NOTIFICATION_ABOUT_NEW_MATERIAL_PRIMARY = createUniqueKey(TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL, "KEY_notification_about_new_material_PRIMARY", TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL.NOTIFICATION_ID);
        public static final UniqueKey<RNotificationAboutNewModificationRecord> KEY_NOTIFICATION_ABOUT_NEW_MODIFICATION_PRIMARY = createUniqueKey(TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION, "KEY_notification_about_new_modification_PRIMARY", TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION.NOTIFICATION_ID);
        public static final UniqueKey<RNotificationAboutSubcommentRecord> KEY_NOTIFICATION_ABOUT_SUBCOMMENT_PRIMARY = createUniqueKey(TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT, "KEY_notification_about_subcomment_PRIMARY", TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT.NOTIFICATION_ID);
        public static final UniqueKey<RNotificationTypeRecord> KEY_NOTIFICATION_TYPE_PRIMARY = createUniqueKey(TNotificationType.NOTIFICATION_TYPE, "KEY_notification_type_PRIMARY", TNotificationType.NOTIFICATION_TYPE.ID);
        public static final UniqueKey<RNotificationWithoutReasonReferenceRecord> KEY_NOTIFICATION_WITHOUT_REASON_REFERENCE_PRIMARY = createUniqueKey(TNotificationWithoutReasonReference.NOTIFICATION_WITHOUT_REASON_REFERENCE, "KEY_notification_without_reason_reference_PRIMARY", TNotificationWithoutReasonReference.NOTIFICATION_WITHOUT_REASON_REFERENCE.NOTIFICATION_ID);
        public static final UniqueKey<RObjectStorageFileRecord> KEY_OBJECT_STORAGE_FILE_PRIMARY = createUniqueKey(TObjectStorageFile.OBJECT_STORAGE_FILE, "KEY_object_storage_file_PRIMARY", TObjectStorageFile.OBJECT_STORAGE_FILE.ID);
        public static final UniqueKey<RSectionRecord> KEY_SECTION_PRIMARY = createUniqueKey(TSection.SECTION, "KEY_section_PRIMARY", TSection.SECTION.ID);
        public static final UniqueKey<RSubscriptionRecord> KEY_SUBSCRIPTION_ALL_COLUMN_UNIQUE = createUniqueKey(TSubscription.SUBSCRIPTION, "KEY_subscription_all_column_UNIQUE", TSubscription.SUBSCRIPTION.SUBSCRIBER_ID, TSubscription.SUBSCRIPTION.AUTHORITY_ID);
        public static final UniqueKey<RUserRecord> KEY_USER_PRIMARY = createUniqueKey(TUser.USER, "KEY_user_PRIMARY", TUser.USER.ID);
        public static final UniqueKey<RUserRecord> KEY_USER_AVATAR_UNIQUE = createUniqueKey(TUser.USER, "KEY_user_avatar_UNIQUE", TUser.USER.AVATAR);
        public static final UniqueKey<RUserRecord> KEY_USER_EMAIL_UNIQUE = createUniqueKey(TUser.USER, "KEY_user_email_UNIQUE", TUser.USER.EMAIL);
        public static final UniqueKey<RUserRecord> KEY_USER_LOGIN_UNIQUE = createUniqueKey(TUser.USER, "KEY_user_login_UNIQUE", TUser.USER.LOGIN);
        public static final UniqueKey<RUserBookmarkRecord> KEY_USER_BOOKMARK_PRIMARY = createUniqueKey(TUserBookmark.USER_BOOKMARK, "KEY_user_bookmark_PRIMARY", TUserBookmark.USER_BOOKMARK.USER_ID, TUserBookmark.USER_BOOKMARK.MATERIAL_ID);
        public static final UniqueKey<RUserDeferredMaterialRecord> KEY_USER_DEFERRED_MATERIAL_PRIMARY = createUniqueKey(TUserDeferredMaterial.USER_DEFERRED_MATERIAL, "KEY_user_deferred_material_PRIMARY", TUserDeferredMaterial.USER_DEFERRED_MATERIAL.USER_ID, TUserDeferredMaterial.USER_DEFERRED_MATERIAL.MATERIAL_ID);
        public static final UniqueKey<RUserDesirableSectionRecord> KEY_USER_DESIRABLE_SECTION_PRIMARY = createUniqueKey(TUserDesirableSection.USER_DESIRABLE_SECTION, "KEY_user_desirable_section_PRIMARY", TUserDesirableSection.USER_DESIRABLE_SECTION.USER_ID, TUserDesirableSection.USER_DESIRABLE_SECTION.SECTION_ID);
        public static final UniqueKey<RUserFavouriteMaterialRecord> KEY_USER_FAVOURITE_MATERIAL_PRIMARY = createUniqueKey(TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL, "KEY_user_favourite_material_PRIMARY", TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL.USER_ID, TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL.MATERIAL_ID);
        public static final UniqueKey<RUserSavedAttachmentRecord> KEY_USER_SAVED_ATTACHMENT_PRIMARY = createUniqueKey(TUserSavedAttachment.USER_SAVED_ATTACHMENT, "KEY_user_saved_attachment_PRIMARY", TUserSavedAttachment.USER_SAVED_ATTACHMENT.USER_ID, TUserSavedAttachment.USER_SAVED_ATTACHMENT.ATTACHMENT_OBJECT_STORAGE_FILE_ID);
        public static final UniqueKey<RUserStatusRecord> KEY_USER_STATUS_PRIMARY = createUniqueKey(TUserStatus.USER_STATUS, "KEY_user_status_PRIMARY", TUserStatus.USER_STATUS.ID);
        public static final UniqueKey<RUserStatusRecord> KEY_USER_STATUS_STATUS_NAME_UNIQUE = createUniqueKey(TUserStatus.USER_STATUS, "KEY_user_status_status_name_UNIQUE", TUserStatus.USER_STATUS.STATUS_NAME);
        public static final UniqueKey<RUserStatusInSectionRecord> KEY_USER_STATUS_IN_SECTION_PRIMARY = createUniqueKey(TUserStatusInSection.USER_STATUS_IN_SECTION, "KEY_user_status_in_section_PRIMARY", TUserStatusInSection.USER_STATUS_IN_SECTION.USER_ID, TUserStatusInSection.USER_STATUS_IN_SECTION.SECTION_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<RCommentaryRecord, RUserRecord> FK_COMMENTARY_AUTHOR_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TCommentary.COMMENTARY, "fk_commentary_author_user_id", TCommentary.COMMENTARY.AUTHOR_USER_ID);
        public static final ForeignKey<RCommentaryRecord, RMaterialRecord> FK_COMMENTARY_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TCommentary.COMMENTARY, "fk_commentary_material_id", TCommentary.COMMENTARY.MATERIAL_ID);
        public static final ForeignKey<RCommentaryRecord, RCommentaryRecord> FK_COMMENTARY_POSSIBLE_PARENT_COMMENTARY_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COMMENTARY_PRIMARY, TCommentary.COMMENTARY, "fk_commentary_possible_parent_commentary_id", TCommentary.COMMENTARY.PARENT_COMMENTARY_ID);
        public static final ForeignKey<RCommentaryRecord, RContentDataRecord> FK_COMMENTARY_COMMENTARY_CONTENT_DATA = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_CONTENT_DATA_PRIMARY, TCommentary.COMMENTARY, "fk_commentary_commentary_content_data", TCommentary.COMMENTARY.CONTENT_DATA_ID);
        public static final ForeignKey<RCommentaryMarkRecord, RCommentaryRecord> FK_COMMENTARY_MARK_COMMENTARY_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COMMENTARY_PRIMARY, TCommentaryMark.COMMENTARY_MARK, "fk_commentary_mark_commentary_id", TCommentaryMark.COMMENTARY_MARK.COMMENTARY_ID);
        public static final ForeignKey<RCommentaryMarkRecord, RUserRecord> FK_COMMENTARY_MARK_SETTER_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TCommentaryMark.COMMENTARY_MARK, "fk_commentary_mark_setter_user_id", TCommentaryMark.COMMENTARY_MARK.SETTER_USER_ID);
        public static final ForeignKey<RCourseRecord, RUserRecord> FK_COURSE_CREATOR_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TCourse.COURSE, "fk_course_creator_user_id", TCourse.COURSE.CREATOR_USER_ID);
        public static final ForeignKey<RCourseRecord, RSectionRecord> FK_COURSE_SECTION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TCourse.COURSE, "fk_course_section_id", TCourse.COURSE.SECTION_ID);
        public static final ForeignKey<RGenericNotificationRecord, RUserRecord> FK_GENERIC_NOTIFICATION_RECEIVER_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TGenericNotification.GENERIC_NOTIFICATION, "fk_generic_notification_receiver_user_id", TGenericNotification.GENERIC_NOTIFICATION.RECEIVER_USER_ID);
        public static final ForeignKey<RGenericNotificationRecord, RNotificationTypeRecord> FK_GENERIC_NOTIFICATION_TYPE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_NOTIFICATION_TYPE_PRIMARY, TGenericNotification.GENERIC_NOTIFICATION, "fk_generic_notification_type_id", TGenericNotification.GENERIC_NOTIFICATION.TYPE_ID);
        public static final ForeignKey<RInCommentaryModeratorRequestRecord, RCommentaryRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_COMMENTARY_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COMMENTARY_PRIMARY, TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST, "fk_in_commentary_moderator_request_commentary_id", TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST.CONMMENTARY_ID);
        public static final ForeignKey<RInCommentaryModeratorRequestRecord, RMaterialRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST, "fk_in_commentary_moderator_request_material_id", TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST.MATERIAL_ID);
        public static final ForeignKey<RInCommentaryModeratorRequestRecord, RSectionRecord> FK_IN_COMMENTARY_MODERATOR_REQUEST_SECTION_OF_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST, "fk_in_commentary_moderator_request_section_of_material_id", TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST.SECTION_OF_MATERIAL_ID);
        public static final ForeignKey<RMaterialRecord, RUserRecord> FK_MATERIAL_AUTHOR_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TMaterial.MATERIAL, "fk_material_author_user_id", TMaterial.MATERIAL.AUTHOR_USER_ID);
        public static final ForeignKey<RMaterialRecord, RMaterialStateRecord> FK_MATERIAL_STATE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_STATE_PRIMARY, TMaterial.MATERIAL, "fk_material_state_id", TMaterial.MATERIAL.STATE_ID);
        public static final ForeignKey<RMaterialRecord, RMaterialFormatRecord> FK_MATERIAL_FORMAT_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_FORMAT_PRIMARY, TMaterial.MATERIAL, "fk_material_format_id", TMaterial.MATERIAL.FORMAT_ID);
        public static final ForeignKey<RMaterialRecord, RCourseRecord> FK_MATERIAL_POSSIBLE_COURSE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COURSE_PRIMARY, TMaterial.MATERIAL, "fk_material_possible_course_id", TMaterial.MATERIAL.COURSE_ID);
        public static final ForeignKey<RMaterialRecord, RSectionRecord> FK_MATERIAL_MATERIAL_SECTION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TMaterial.MATERIAL, "fk_material_material_section_id", TMaterial.MATERIAL.SECTION_ID);
        public static final ForeignKey<RMaterialRecord, RContentDataRecord> FK_MATERIAL_MATERIAL_CONTENT_DATA_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_CONTENT_DATA_PRIMARY, TMaterial.MATERIAL, "fk_material_material_content_data_id", TMaterial.MATERIAL.CONTENT_DATA_ID);
        public static final ForeignKey<RMaterialAttachmentRecord, RMaterialRecord> FK_MATERIAL_ATTACHMENT_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TMaterialAttachment.MATERIAL_ATTACHMENT, "fk_material_attachment_material_id", TMaterialAttachment.MATERIAL_ATTACHMENT.MATERIAL_ID);
        public static final ForeignKey<RMaterialAttachmentRecord, RObjectStorageFileRecord> FK_MATERIAL_ATTACHMENT_OBJECT_STORAGE_FILE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_OBJECT_STORAGE_FILE_PRIMARY, TMaterialAttachment.MATERIAL_ATTACHMENT, "fk_material_attachment_object_storage_file_id", TMaterialAttachment.MATERIAL_ATTACHMENT.OBJECT_STORAGE_FILE_ID);
        public static final ForeignKey<RMaterialMarkRecord, RMaterialRecord> FK_MATERIAL_MARK_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TMaterialMark.MATERIAL_MARK, "fk_material_mark_material_id", TMaterialMark.MATERIAL_MARK.MATERIAL_ID);
        public static final ForeignKey<RMaterialMarkRecord, RUserRecord> FK_MATERIAL_MARK_SETTER_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TMaterialMark.MATERIAL_MARK, "fk_material_mark_setter_user_id", TMaterialMark.MATERIAL_MARK.SETTER_USER_ID);
        public static final ForeignKey<RMaterialRecommendationRecord, RMaterialRecord> FK_MATERIAL_RECOMMENDATION_SOURCE_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TMaterialRecommendation.MATERIAL_RECOMMENDATION, "fk_material_recommendation_source_material_id", TMaterialRecommendation.MATERIAL_RECOMMENDATION.SOURCE_MATERIAL_ID);
        public static final ForeignKey<RMaterialRecommendationRecord, RMaterialRecord> FK_MATERIAL_RECOMMENDATION_RECOMMENDED_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TMaterialRecommendation.MATERIAL_RECOMMENDATION, "fk_material_recommendation_recommended_material_id", TMaterialRecommendation.MATERIAL_RECOMMENDATION.RECOMMENDED_MATERIAL_ID);
        public static final ForeignKey<RMaterialViewRecord, RUserRecord> FK_MATERIAL_VIEW_VIEWER_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TMaterialView.MATERIAL_VIEW, "fk_material_view_viewer_user_id", TMaterialView.MATERIAL_VIEW.VIEWER_USER_ID);
        public static final ForeignKey<RMaterialViewRecord, RMaterialRecord> FK_MATERIAL_VIEW_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TMaterialView.MATERIAL_VIEW, "fk_material_view_material_id", TMaterialView.MATERIAL_VIEW.MATERIAL_ID);
        public static final ForeignKey<RModificationRecord, RMaterialRecord> FK_MODIFICATION_SOURCE_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TModification.MODIFICATION, "fk_modification_source_material_id", TModification.MODIFICATION.SOURCE_MATERIAL_ID);
        public static final ForeignKey<RModificationRecord, RUserRecord> FK_MODIFICATION_REQUESTER_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TModification.MODIFICATION, "fk_modification_requester_user_id", TModification.MODIFICATION.REQUESTER_USER_ID);
        public static final ForeignKey<RNotificationAboutMaterialAchievementRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_NOTIFICATION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_GENERIC_NOTIFICATION_PRIMARY, TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT, "fk_notification_about_material_achievement_notification_id", TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT.NOTIFICATION_ID);
        public static final ForeignKey<RNotificationAboutMaterialAchievementRecord, RMaterialRecord> FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_REASON_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT, "fk_notification_about_material_achievement_reason_id", TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT.REASON_ID);
        public static final ForeignKey<RNotificationAboutNewMaterialRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_NEW_MATERIAL_NOTIFICATION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_GENERIC_NOTIFICATION_PRIMARY, TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL, "fk_notification_about_new_material_notification_id", TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL.NOTIFICATION_ID);
        public static final ForeignKey<RNotificationAboutNewMaterialRecord, RMaterialRecord> FK_NOTIFICATION_ABOUT_NEW_MATERIAL_REASON_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL, "fk_notification_about_new_material_reason_id", TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL.REASON_ID);
        public static final ForeignKey<RNotificationAboutNewModificationRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_NOTIFICATION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_GENERIC_NOTIFICATION_PRIMARY, TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION, "fk_notification_about_new_modification_notification_id", TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION.NOTIFICATION_ID);
        public static final ForeignKey<RNotificationAboutNewModificationRecord, RModificationRecord> FK_NOTIFICATION_ABOUT_NEW_MODIFICATION_REASON_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MODIFICATION_PRIMARY, TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION, "fk_notification_about_new_modification_reason_id", TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION.REASON_ID);
        public static final ForeignKey<RNotificationAboutSubcommentRecord, RGenericNotificationRecord> FK_NOTIFICATION_ABOUT_SUBCOMMENT_NOTIFICATION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_GENERIC_NOTIFICATION_PRIMARY, TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT, "fk_notification_about_subcomment_notification_id", TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT.NOTIFICATION_ID);
        public static final ForeignKey<RNotificationAboutSubcommentRecord, RCommentaryRecord> FK_NOTIFICATION_ABOUT_SUBCOMMENT_REASON_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COMMENTARY_PRIMARY, TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT, "fk_notification_about_subcomment_reason_id", TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT.REASON_ID);
        public static final ForeignKey<RNotificationWithoutReasonReferenceRecord, RGenericNotificationRecord> FK_NOTIFICATION_WITHOUT_REASON_REFERENCE_NOTIFICATION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_GENERIC_NOTIFICATION_PRIMARY, TNotificationWithoutReasonReference.NOTIFICATION_WITHOUT_REASON_REFERENCE, "fk_notification_without_reason_reference_notification_id", TNotificationWithoutReasonReference.NOTIFICATION_WITHOUT_REASON_REFERENCE.NOTIFICATION_ID);
        public static final ForeignKey<RSectionRecord, RSectionRecord> FK_SECTION_POSSIBLE_SUPER_SECTION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TSection.SECTION, "fk_section_possible_super_section_id", TSection.SECTION.SUPER_SECTION_ID);
        public static final ForeignKey<RSubscriptionRecord, RUserRecord> FK_SUBSCRIPTION_SUBSCRIBER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TSubscription.SUBSCRIPTION, "fk_subscription_subscriber_id", TSubscription.SUBSCRIPTION.SUBSCRIBER_ID);
        public static final ForeignKey<RSubscriptionRecord, RUserRecord> FK_SUBSCRIPTION_AUTHORITY_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TSubscription.SUBSCRIPTION, "fk_subscription_authority_id", TSubscription.SUBSCRIPTION.AUTHORITY_ID);
        public static final ForeignKey<RUserRecord, RObjectStorageFileRecord> FK_USER_AVATAR_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_OBJECT_STORAGE_FILE_PRIMARY, TUser.USER, "fk_user_avatar_id", TUser.USER.AVATAR);
        public static final ForeignKey<RUserRecord, RUserStatusRecord> FK_USER_STATUS_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_STATUS_PRIMARY, TUser.USER, "fk_user_status_id", TUser.USER.STATUS_ID);
        public static final ForeignKey<RUserBookmarkRecord, RUserRecord> FK_USER_BOOKMARK_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserBookmark.USER_BOOKMARK, "fk_user_bookmark_user_id", TUserBookmark.USER_BOOKMARK.USER_ID);
        public static final ForeignKey<RUserBookmarkRecord, RMaterialRecord> FK_USER_BOOKMARK_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TUserBookmark.USER_BOOKMARK, "fk_user_bookmark_material_id", TUserBookmark.USER_BOOKMARK.MATERIAL_ID);
        public static final ForeignKey<RUserBookmarkRecord, RCourseRecord> FK_USER_BOOKMARK_POSSIBLE_COURSE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COURSE_PRIMARY, TUserBookmark.USER_BOOKMARK, "fk_user_bookmark_possible_course_id", TUserBookmark.USER_BOOKMARK.POSSIBLE_COURSE_ID);
        public static final ForeignKey<RUserDeferredMaterialRecord, RUserRecord> FK_USER_DEFERRED_MATERIAL_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserDeferredMaterial.USER_DEFERRED_MATERIAL, "fk_user_deferred_material_user_id", TUserDeferredMaterial.USER_DEFERRED_MATERIAL.USER_ID);
        public static final ForeignKey<RUserDeferredMaterialRecord, RMaterialRecord> FK_USER_DEFERRED_MATERIAL_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TUserDeferredMaterial.USER_DEFERRED_MATERIAL, "fk_user_deferred_material_material_id", TUserDeferredMaterial.USER_DEFERRED_MATERIAL.MATERIAL_ID);
        public static final ForeignKey<RUserDeferredMaterialRecord, RCourseRecord> FK_USER_DEFERRED_MATERIAL_POSSIBLE_COURSE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COURSE_PRIMARY, TUserDeferredMaterial.USER_DEFERRED_MATERIAL, "fk_user_deferred_material_possible_course_id", TUserDeferredMaterial.USER_DEFERRED_MATERIAL.POSSIBLE_COURSE_ID);
        public static final ForeignKey<RUserDesirableSectionRecord, RUserRecord> FK_USER_DESIRABLE_SECTION_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserDesirableSection.USER_DESIRABLE_SECTION, "fk_user_desirable_section_user_id", TUserDesirableSection.USER_DESIRABLE_SECTION.USER_ID);
        public static final ForeignKey<RUserDesirableSectionRecord, RSectionRecord> FK_USER_DESIRABLE_SECTION_SECTION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TUserDesirableSection.USER_DESIRABLE_SECTION, "fk_user_desirable_section_section_id", TUserDesirableSection.USER_DESIRABLE_SECTION.SECTION_ID);
        public static final ForeignKey<RUserFavouriteMaterialRecord, RUserRecord> FK_USER_FAVOURITE_MATERIAL_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL, "fk_user_favourite_material_user_id", TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL.USER_ID);
        public static final ForeignKey<RUserFavouriteMaterialRecord, RMaterialRecord> FK_USER_FAVOURITE_MATERIAL_MATERIAL_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_PRIMARY, TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL, "fk_user_favourite_material_material_id", TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL.MATERIAL_ID);
        public static final ForeignKey<RUserFavouriteMaterialRecord, RCourseRecord> FK_USER_FAVOURITE_MATERIAL_POSSIBLE_COURSE_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_COURSE_PRIMARY, TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL, "fk_user_favourite_material_possible_course_id", TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL.POSSIBLE_COURSE_ID);
        public static final ForeignKey<RUserSavedAttachmentRecord, RUserRecord> FK_USER_SAVED_ATTACHMENT_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserSavedAttachment.USER_SAVED_ATTACHMENT, "fk_user_saved_attachment_user_id", TUserSavedAttachment.USER_SAVED_ATTACHMENT.USER_ID);
        public static final ForeignKey<RUserSavedAttachmentRecord, RMaterialAttachmentRecord> FK_USER_SAVED_ATTACHMENT_ATTACHMENT_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_MATERIAL_ATTACHMENT_PRIMARY, TUserSavedAttachment.USER_SAVED_ATTACHMENT, "fk_user_saved_attachment_attachment_id", TUserSavedAttachment.USER_SAVED_ATTACHMENT.ATTACHMENT_OBJECT_STORAGE_FILE_ID);
        public static final ForeignKey<RUserStatusInSectionRecord, RUserRecord> FK_USER_STATUS_IN_SECTION_USER_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_USER_PRIMARY, TUserStatusInSection.USER_STATUS_IN_SECTION, "fk_user_status_in_section_user_id", TUserStatusInSection.USER_STATUS_IN_SECTION.USER_ID);
        public static final ForeignKey<RUserStatusInSectionRecord, RSectionRecord> FK_USER_STATUS_IN_SECTION_SECTION_ID = createForeignKey(ua.ddovgal.brainshareApi.jooq.Keys.KEY_SECTION_PRIMARY, TUserStatusInSection.USER_STATUS_IN_SECTION, "fk_user_status_in_section_section_id", TUserStatusInSection.USER_STATUS_IN_SECTION.SECTION_ID);
    }
}
