/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq;


import ua.ddovgal.brainshareApi.jooq.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in brainshare_dev
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>brainshare_dev.commentary</code>.
     */
    public static final TCommentary COMMENTARY = ua.ddovgal.brainshareApi.jooq.tables.TCommentary.COMMENTARY;

    /**
     * The table <code>brainshare_dev.commentary_mark</code>.
     */
    public static final TCommentaryMark COMMENTARY_MARK = ua.ddovgal.brainshareApi.jooq.tables.TCommentaryMark.COMMENTARY_MARK;

    /**
     * The table <code>brainshare_dev.content_data</code>.
     */
    public static final TContentData CONTENT_DATA = ua.ddovgal.brainshareApi.jooq.tables.TContentData.CONTENT_DATA;

    /**
     * The table <code>brainshare_dev.course</code>.
     */
    public static final TCourse COURSE = ua.ddovgal.brainshareApi.jooq.tables.TCourse.COURSE;

    /**
     * The table <code>brainshare_dev.generic_notification</code>.
     */
    public static final TGenericNotification GENERIC_NOTIFICATION = ua.ddovgal.brainshareApi.jooq.tables.TGenericNotification.GENERIC_NOTIFICATION;

    /**
     * The table <code>brainshare_dev.in_commentary_moderator_request</code>.
     */
    public static final TInCommentaryModeratorRequest IN_COMMENTARY_MODERATOR_REQUEST = ua.ddovgal.brainshareApi.jooq.tables.TInCommentaryModeratorRequest.IN_COMMENTARY_MODERATOR_REQUEST;

    /**
     * The table <code>brainshare_dev.material</code>.
     */
    public static final TMaterial MATERIAL = ua.ddovgal.brainshareApi.jooq.tables.TMaterial.MATERIAL;

    /**
     * The table <code>brainshare_dev.material_attachment</code>.
     */
    public static final TMaterialAttachment MATERIAL_ATTACHMENT = ua.ddovgal.brainshareApi.jooq.tables.TMaterialAttachment.MATERIAL_ATTACHMENT;

    /**
     * The table <code>brainshare_dev.material_format</code>.
     */
    public static final TMaterialFormat MATERIAL_FORMAT = ua.ddovgal.brainshareApi.jooq.tables.TMaterialFormat.MATERIAL_FORMAT;

    /**
     * The table <code>brainshare_dev.material_mark</code>.
     */
    public static final TMaterialMark MATERIAL_MARK = ua.ddovgal.brainshareApi.jooq.tables.TMaterialMark.MATERIAL_MARK;

    /**
     * The table <code>brainshare_dev.material_recommendation</code>.
     */
    public static final TMaterialRecommendation MATERIAL_RECOMMENDATION = ua.ddovgal.brainshareApi.jooq.tables.TMaterialRecommendation.MATERIAL_RECOMMENDATION;

    /**
     * The table <code>brainshare_dev.material_state</code>.
     */
    public static final TMaterialState MATERIAL_STATE = ua.ddovgal.brainshareApi.jooq.tables.TMaterialState.MATERIAL_STATE;

    /**
     * The table <code>brainshare_dev.material_view</code>.
     */
    public static final TMaterialView MATERIAL_VIEW = ua.ddovgal.brainshareApi.jooq.tables.TMaterialView.MATERIAL_VIEW;

    /**
     * The table <code>brainshare_dev.modification</code>.
     */
    public static final TModification MODIFICATION = ua.ddovgal.brainshareApi.jooq.tables.TModification.MODIFICATION;

    /**
     * The table <code>brainshare_dev.notification_about_material_achievement</code>.
     */
    public static final TNotificationAboutMaterialAchievement NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT = ua.ddovgal.brainshareApi.jooq.tables.TNotificationAboutMaterialAchievement.NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT;

    /**
     * The table <code>brainshare_dev.notification_about_new_material</code>.
     */
    public static final TNotificationAboutNewMaterial NOTIFICATION_ABOUT_NEW_MATERIAL = ua.ddovgal.brainshareApi.jooq.tables.TNotificationAboutNewMaterial.NOTIFICATION_ABOUT_NEW_MATERIAL;

    /**
     * The table <code>brainshare_dev.notification_about_new_modification</code>.
     */
    public static final TNotificationAboutNewModification NOTIFICATION_ABOUT_NEW_MODIFICATION = ua.ddovgal.brainshareApi.jooq.tables.TNotificationAboutNewModification.NOTIFICATION_ABOUT_NEW_MODIFICATION;

    /**
     * The table <code>brainshare_dev.notification_about_subcomment</code>.
     */
    public static final TNotificationAboutSubcomment NOTIFICATION_ABOUT_SUBCOMMENT = ua.ddovgal.brainshareApi.jooq.tables.TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT;

    /**
     * The table <code>brainshare_dev.notification_type</code>.
     */
    public static final TNotificationType NOTIFICATION_TYPE = ua.ddovgal.brainshareApi.jooq.tables.TNotificationType.NOTIFICATION_TYPE;

    /**
     * The table <code>brainshare_dev.notification_without_reason_reference</code>.
     */
    public static final TNotificationWithoutReasonReference NOTIFICATION_WITHOUT_REASON_REFERENCE = ua.ddovgal.brainshareApi.jooq.tables.TNotificationWithoutReasonReference.NOTIFICATION_WITHOUT_REASON_REFERENCE;

    /**
     * The table <code>brainshare_dev.object_storage_file</code>.
     */
    public static final TObjectStorageFile OBJECT_STORAGE_FILE = ua.ddovgal.brainshareApi.jooq.tables.TObjectStorageFile.OBJECT_STORAGE_FILE;

    /**
     * The table <code>brainshare_dev.section</code>.
     */
    public static final TSection SECTION = ua.ddovgal.brainshareApi.jooq.tables.TSection.SECTION;

    /**
     * The table <code>brainshare_dev.subscription</code>.
     */
    public static final TSubscription SUBSCRIPTION = ua.ddovgal.brainshareApi.jooq.tables.TSubscription.SUBSCRIPTION;

    /**
     * The table <code>brainshare_dev.user</code>.
     */
    public static final TUser USER = ua.ddovgal.brainshareApi.jooq.tables.TUser.USER;

    /**
     * The table <code>brainshare_dev.user_bookmark</code>.
     */
    public static final TUserBookmark USER_BOOKMARK = ua.ddovgal.brainshareApi.jooq.tables.TUserBookmark.USER_BOOKMARK;

    /**
     * The table <code>brainshare_dev.user_deferred_material</code>.
     */
    public static final TUserDeferredMaterial USER_DEFERRED_MATERIAL = ua.ddovgal.brainshareApi.jooq.tables.TUserDeferredMaterial.USER_DEFERRED_MATERIAL;

    /**
     * The table <code>brainshare_dev.user_desirable_section</code>.
     */
    public static final TUserDesirableSection USER_DESIRABLE_SECTION = ua.ddovgal.brainshareApi.jooq.tables.TUserDesirableSection.USER_DESIRABLE_SECTION;

    /**
     * The table <code>brainshare_dev.user_favourite_material</code>.
     */
    public static final TUserFavouriteMaterial USER_FAVOURITE_MATERIAL = ua.ddovgal.brainshareApi.jooq.tables.TUserFavouriteMaterial.USER_FAVOURITE_MATERIAL;

    /**
     * The table <code>brainshare_dev.user_saved_attachment</code>.
     */
    public static final TUserSavedAttachment USER_SAVED_ATTACHMENT = ua.ddovgal.brainshareApi.jooq.tables.TUserSavedAttachment.USER_SAVED_ATTACHMENT;

    /**
     * The table <code>brainshare_dev.user_status</code>.
     */
    public static final TUserStatus USER_STATUS = ua.ddovgal.brainshareApi.jooq.tables.TUserStatus.USER_STATUS;

    /**
     * The table <code>brainshare_dev.user_status_in_section</code>.
     */
    public static final TUserStatusInSection USER_STATUS_IN_SECTION = ua.ddovgal.brainshareApi.jooq.tables.TUserStatusInSection.USER_STATUS_IN_SECTION;
}
