/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CommentaryMark implements Serializable {

    private static final long serialVersionUID = 455361223;

    private ULong commentaryId;
    private ULong setterUserId;
    private Byte isUpMark;

    public CommentaryMark() {
    }

    public CommentaryMark(CommentaryMark value) {
        this.commentaryId = value.commentaryId;
        this.setterUserId = value.setterUserId;
        this.isUpMark = value.isUpMark;
    }

    public CommentaryMark(
            ULong commentaryId,
            ULong setterUserId,
            Byte isUpMark
    ) {
        this.commentaryId = commentaryId;
        this.setterUserId = setterUserId;
        this.isUpMark = isUpMark;
    }

    public ULong getCommentaryId() {
        return this.commentaryId;
    }

    public void setCommentaryId(ULong commentaryId) {
        this.commentaryId = commentaryId;
    }

    public ULong getSetterUserId() {
        return this.setterUserId;
    }

    public void setSetterUserId(ULong setterUserId) {
        this.setterUserId = setterUserId;
    }

    public Byte getIsUpMark() {
        return this.isUpMark;
    }

    public void setIsUpMark(Byte isUpMark) {
        this.isUpMark = isUpMark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommentaryMark (");

        sb.append(commentaryId);
        sb.append(", ").append(setterUserId);
        sb.append(", ").append(isUpMark);

        sb.append(")");
        return sb.toString();
    }
}
