/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ContentData implements Serializable {

    private static final long serialVersionUID = 1286112167;

    private ULong id;
    private Object dataJson;

    public ContentData() {
    }

    public ContentData(ContentData value) {
        this.id = value.id;
        this.dataJson = value.dataJson;
    }

    public ContentData(
            ULong id,
            Object dataJson
    ) {
        this.id = id;
        this.dataJson = dataJson;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Object getDataJson() {
        return this.dataJson;
    }

    public void setDataJson(Object dataJson) {
        this.dataJson = dataJson;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContentData (");

        sb.append(id);
        sb.append(", ").append(dataJson);

        sb.append(")");
        return sb.toString();
    }
}
