/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.jooq.types.UShort;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Course implements Serializable {

    private static final long serialVersionUID = 1444484435;

    private ULong id;
    private String name;
    private ULong creatorUserId;
    private UShort materialsInsideCount;
    private String description;
    private UInteger sectionId;

    public Course() {
    }

    public Course(Course value) {
        this.id = value.id;
        this.name = value.name;
        this.creatorUserId = value.creatorUserId;
        this.materialsInsideCount = value.materialsInsideCount;
        this.description = value.description;
        this.sectionId = value.sectionId;
    }

    public Course(
            ULong id,
            String name,
            ULong creatorUserId,
            UShort materialsInsideCount,
            String description,
            UInteger sectionId
    ) {
        this.id = id;
        this.name = name;
        this.creatorUserId = creatorUserId;
        this.materialsInsideCount = materialsInsideCount;
        this.description = description;
        this.sectionId = sectionId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ULong getCreatorUserId() {
        return this.creatorUserId;
    }

    public void setCreatorUserId(ULong creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    public UShort getMaterialsInsideCount() {
        return this.materialsInsideCount;
    }

    public void setMaterialsInsideCount(UShort materialsInsideCount) {
        this.materialsInsideCount = materialsInsideCount;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public UInteger getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(UInteger sectionId) {
        this.sectionId = sectionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Course (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(creatorUserId);
        sb.append(", ").append(materialsInsideCount);
        sb.append(", ").append(description);
        sb.append(", ").append(sectionId);

        sb.append(")");
        return sb.toString();
    }
}
