/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InCommentaryModeratorRequest implements Serializable {

    private static final long serialVersionUID = -871638839;

    private ULong id;
    private ULong conmmentaryId;
    private ULong materialId;
    private UInteger sectionOfMaterialId;
    private Byte isConcideredBySomeone;

    public InCommentaryModeratorRequest() {
    }

    public InCommentaryModeratorRequest(InCommentaryModeratorRequest value) {
        this.id = value.id;
        this.conmmentaryId = value.conmmentaryId;
        this.materialId = value.materialId;
        this.sectionOfMaterialId = value.sectionOfMaterialId;
        this.isConcideredBySomeone = value.isConcideredBySomeone;
    }

    public InCommentaryModeratorRequest(
            ULong id,
            ULong conmmentaryId,
            ULong materialId,
            UInteger sectionOfMaterialId,
            Byte isConcideredBySomeone
    ) {
        this.id = id;
        this.conmmentaryId = conmmentaryId;
        this.materialId = materialId;
        this.sectionOfMaterialId = sectionOfMaterialId;
        this.isConcideredBySomeone = isConcideredBySomeone;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public ULong getConmmentaryId() {
        return this.conmmentaryId;
    }

    public void setConmmentaryId(ULong conmmentaryId) {
        this.conmmentaryId = conmmentaryId;
    }

    public ULong getMaterialId() {
        return this.materialId;
    }

    public void setMaterialId(ULong materialId) {
        this.materialId = materialId;
    }

    public UInteger getSectionOfMaterialId() {
        return this.sectionOfMaterialId;
    }

    public void setSectionOfMaterialId(UInteger sectionOfMaterialId) {
        this.sectionOfMaterialId = sectionOfMaterialId;
    }

    public Byte getIsConcideredBySomeone() {
        return this.isConcideredBySomeone;
    }

    public void setIsConcideredBySomeone(Byte isConcideredBySomeone) {
        this.isConcideredBySomeone = isConcideredBySomeone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InCommentaryModeratorRequest (");

        sb.append(id);
        sb.append(", ").append(conmmentaryId);
        sb.append(", ").append(materialId);
        sb.append(", ").append(sectionOfMaterialId);
        sb.append(", ").append(isConcideredBySomeone);

        sb.append(")");
        return sb.toString();
    }
}
