/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Material implements Serializable {

    private static final long serialVersionUID = -890425977;

    private ULong id;
    private String title;
    private ULong authorUserId;
    private Integer ratio;
    private Byte hasLowPriority;
    private UInteger positiveMarkCount;
    private UInteger negativeMarkCount;
    private UInteger stateId;
    private UInteger approvalValue;
    private Timestamp creationDatetime;
    private UInteger formatId;
    private ULong courseId;
    private UInteger sectionId;
    private String tagsSeparatedByComma;
    private Object previewContentDataJson;
    private ULong contentDataId;
    private UInteger viewCount;

    public Material() {
    }

    public Material(Material value) {
        this.id = value.id;
        this.title = value.title;
        this.authorUserId = value.authorUserId;
        this.ratio = value.ratio;
        this.hasLowPriority = value.hasLowPriority;
        this.positiveMarkCount = value.positiveMarkCount;
        this.negativeMarkCount = value.negativeMarkCount;
        this.stateId = value.stateId;
        this.approvalValue = value.approvalValue;
        this.creationDatetime = value.creationDatetime;
        this.formatId = value.formatId;
        this.courseId = value.courseId;
        this.sectionId = value.sectionId;
        this.tagsSeparatedByComma = value.tagsSeparatedByComma;
        this.previewContentDataJson = value.previewContentDataJson;
        this.contentDataId = value.contentDataId;
        this.viewCount = value.viewCount;
    }

    public Material(
            ULong id,
            String title,
            ULong authorUserId,
            Integer ratio,
            Byte hasLowPriority,
            UInteger positiveMarkCount,
            UInteger negativeMarkCount,
            UInteger stateId,
            UInteger approvalValue,
            Timestamp creationDatetime,
            UInteger formatId,
            ULong courseId,
            UInteger sectionId,
            String tagsSeparatedByComma,
            Object previewContentDataJson,
            ULong contentDataId,
            UInteger viewCount
    ) {
        this.id = id;
        this.title = title;
        this.authorUserId = authorUserId;
        this.ratio = ratio;
        this.hasLowPriority = hasLowPriority;
        this.positiveMarkCount = positiveMarkCount;
        this.negativeMarkCount = negativeMarkCount;
        this.stateId = stateId;
        this.approvalValue = approvalValue;
        this.creationDatetime = creationDatetime;
        this.formatId = formatId;
        this.courseId = courseId;
        this.sectionId = sectionId;
        this.tagsSeparatedByComma = tagsSeparatedByComma;
        this.previewContentDataJson = previewContentDataJson;
        this.contentDataId = contentDataId;
        this.viewCount = viewCount;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ULong getAuthorUserId() {
        return this.authorUserId;
    }

    public void setAuthorUserId(ULong authorUserId) {
        this.authorUserId = authorUserId;
    }

    public Integer getRatio() {
        return this.ratio;
    }

    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    public Byte getHasLowPriority() {
        return this.hasLowPriority;
    }

    public void setHasLowPriority(Byte hasLowPriority) {
        this.hasLowPriority = hasLowPriority;
    }

    public UInteger getPositiveMarkCount() {
        return this.positiveMarkCount;
    }

    public void setPositiveMarkCount(UInteger positiveMarkCount) {
        this.positiveMarkCount = positiveMarkCount;
    }

    public UInteger getNegativeMarkCount() {
        return this.negativeMarkCount;
    }

    public void setNegativeMarkCount(UInteger negativeMarkCount) {
        this.negativeMarkCount = negativeMarkCount;
    }

    public UInteger getStateId() {
        return this.stateId;
    }

    public void setStateId(UInteger stateId) {
        this.stateId = stateId;
    }

    public UInteger getApprovalValue() {
        return this.approvalValue;
    }

    public void setApprovalValue(UInteger approvalValue) {
        this.approvalValue = approvalValue;
    }

    public Timestamp getCreationDatetime() {
        return this.creationDatetime;
    }

    public void setCreationDatetime(Timestamp creationDatetime) {
        this.creationDatetime = creationDatetime;
    }

    public UInteger getFormatId() {
        return this.formatId;
    }

    public void setFormatId(UInteger formatId) {
        this.formatId = formatId;
    }

    public ULong getCourseId() {
        return this.courseId;
    }

    public void setCourseId(ULong courseId) {
        this.courseId = courseId;
    }

    public UInteger getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(UInteger sectionId) {
        this.sectionId = sectionId;
    }

    public String getTagsSeparatedByComma() {
        return this.tagsSeparatedByComma;
    }

    public void setTagsSeparatedByComma(String tagsSeparatedByComma) {
        this.tagsSeparatedByComma = tagsSeparatedByComma;
    }

    public Object getPreviewContentDataJson() {
        return this.previewContentDataJson;
    }

    public void setPreviewContentDataJson(Object previewContentDataJson) {
        this.previewContentDataJson = previewContentDataJson;
    }

    public ULong getContentDataId() {
        return this.contentDataId;
    }

    public void setContentDataId(ULong contentDataId) {
        this.contentDataId = contentDataId;
    }

    public UInteger getViewCount() {
        return this.viewCount;
    }

    public void setViewCount(UInteger viewCount) {
        this.viewCount = viewCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Material (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(authorUserId);
        sb.append(", ").append(ratio);
        sb.append(", ").append(hasLowPriority);
        sb.append(", ").append(positiveMarkCount);
        sb.append(", ").append(negativeMarkCount);
        sb.append(", ").append(stateId);
        sb.append(", ").append(approvalValue);
        sb.append(", ").append(creationDatetime);
        sb.append(", ").append(formatId);
        sb.append(", ").append(courseId);
        sb.append(", ").append(sectionId);
        sb.append(", ").append(tagsSeparatedByComma);
        sb.append(", ").append(previewContentDataJson);
        sb.append(", ").append(contentDataId);
        sb.append(", ").append(viewCount);

        sb.append(")");
        return sb.toString();
    }
}
