/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MaterialFormat implements Serializable {

    private static final long serialVersionUID = -696895683;

    private UInteger id;
    private String formatName;
    private String description;

    public MaterialFormat() {
    }

    public MaterialFormat(MaterialFormat value) {
        this.id = value.id;
        this.formatName = value.formatName;
        this.description = value.description;
    }

    public MaterialFormat(
            UInteger id,
            String formatName,
            String description
    ) {
        this.id = id;
        this.formatName = formatName;
        this.description = description;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getFormatName() {
        return this.formatName;
    }

    public void setFormatName(String formatName) {
        this.formatName = formatName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MaterialFormat (");

        sb.append(id);
        sb.append(", ").append(formatName);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
