/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MaterialState implements Serializable {

    private static final long serialVersionUID = 738548077;

    private UInteger id;
    private String stateName;
    private String description;
    private Integer lowBorder;

    public MaterialState() {
    }

    public MaterialState(MaterialState value) {
        this.id = value.id;
        this.stateName = value.stateName;
        this.description = value.description;
        this.lowBorder = value.lowBorder;
    }

    public MaterialState(
            UInteger id,
            String stateName,
            String description,
            Integer lowBorder
    ) {
        this.id = id;
        this.stateName = stateName;
        this.description = description;
        this.lowBorder = lowBorder;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getStateName() {
        return this.stateName;
    }

    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getLowBorder() {
        return this.lowBorder;
    }

    public void setLowBorder(Integer lowBorder) {
        this.lowBorder = lowBorder;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MaterialState (");

        sb.append(id);
        sb.append(", ").append(stateName);
        sb.append(", ").append(description);
        sb.append(", ").append(lowBorder);

        sb.append(")");
        return sb.toString();
    }
}
