/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Modification implements Serializable {

    private static final long serialVersionUID = 974904083;

    private ULong id;
    private ULong sourceMaterialId;
    private ULong requesterUserId;
    private Object modificationDataJson;
    private Byte isAccepted;
    private Timestamp creationDatetime;

    public Modification() {
    }

    public Modification(Modification value) {
        this.id = value.id;
        this.sourceMaterialId = value.sourceMaterialId;
        this.requesterUserId = value.requesterUserId;
        this.modificationDataJson = value.modificationDataJson;
        this.isAccepted = value.isAccepted;
        this.creationDatetime = value.creationDatetime;
    }

    public Modification(
            ULong id,
            ULong sourceMaterialId,
            ULong requesterUserId,
            Object modificationDataJson,
            Byte isAccepted,
            Timestamp creationDatetime
    ) {
        this.id = id;
        this.sourceMaterialId = sourceMaterialId;
        this.requesterUserId = requesterUserId;
        this.modificationDataJson = modificationDataJson;
        this.isAccepted = isAccepted;
        this.creationDatetime = creationDatetime;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public ULong getSourceMaterialId() {
        return this.sourceMaterialId;
    }

    public void setSourceMaterialId(ULong sourceMaterialId) {
        this.sourceMaterialId = sourceMaterialId;
    }

    public ULong getRequesterUserId() {
        return this.requesterUserId;
    }

    public void setRequesterUserId(ULong requesterUserId) {
        this.requesterUserId = requesterUserId;
    }

    public Object getModificationDataJson() {
        return this.modificationDataJson;
    }

    public void setModificationDataJson(Object modificationDataJson) {
        this.modificationDataJson = modificationDataJson;
    }

    public Byte getIsAccepted() {
        return this.isAccepted;
    }

    public void setIsAccepted(Byte isAccepted) {
        this.isAccepted = isAccepted;
    }

    public Timestamp getCreationDatetime() {
        return this.creationDatetime;
    }

    public void setCreationDatetime(Timestamp creationDatetime) {
        this.creationDatetime = creationDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Modification (");

        sb.append(id);
        sb.append(", ").append(sourceMaterialId);
        sb.append(", ").append(requesterUserId);
        sb.append(", ").append(modificationDataJson);
        sb.append(", ").append(isAccepted);
        sb.append(", ").append(creationDatetime);

        sb.append(")");
        return sb.toString();
    }
}
