/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NotificationType implements Serializable {

    private static final long serialVersionUID = 72166676;

    private UInteger id;
    private String typeName;
    private String description;

    public NotificationType() {
    }

    public NotificationType(NotificationType value) {
        this.id = value.id;
        this.typeName = value.typeName;
        this.description = value.description;
    }

    public NotificationType(
            UInteger id,
            String typeName,
            String description
    ) {
        this.id = id;
        this.typeName = typeName;
        this.description = description;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotificationType (");

        sb.append(id);
        sb.append(", ").append(typeName);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
