/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Subscription implements Serializable {

    private static final long serialVersionUID = -1572175783;

    private ULong subscriberId;
    private ULong authorityId;

    public Subscription() {
    }

    public Subscription(Subscription value) {
        this.subscriberId = value.subscriberId;
        this.authorityId = value.authorityId;
    }

    public Subscription(
            ULong subscriberId,
            ULong authorityId
    ) {
        this.subscriberId = subscriberId;
        this.authorityId = authorityId;
    }

    public ULong getSubscriberId() {
        return this.subscriberId;
    }

    public void setSubscriberId(ULong subscriberId) {
        this.subscriberId = subscriberId;
    }

    public ULong getAuthorityId() {
        return this.authorityId;
    }

    public void setAuthorityId(ULong authorityId) {
        this.authorityId = authorityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subscription (");

        sb.append(subscriberId);
        sb.append(", ").append(authorityId);

        sb.append(")");
        return sb.toString();
    }
}
