/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserStatusInSection implements Serializable {

    private static final long serialVersionUID = 1800709661;

    private ULong userId;
    private UInteger sectionId;
    private Integer ratio;
    private String statusValue;

    public UserStatusInSection() {
    }

    public UserStatusInSection(UserStatusInSection value) {
        this.userId = value.userId;
        this.sectionId = value.sectionId;
        this.ratio = value.ratio;
        this.statusValue = value.statusValue;
    }

    public UserStatusInSection(
            ULong userId,
            UInteger sectionId,
            Integer ratio,
            String statusValue
    ) {
        this.userId = userId;
        this.sectionId = sectionId;
        this.ratio = ratio;
        this.statusValue = statusValue;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public UInteger getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(UInteger sectionId) {
        this.sectionId = sectionId;
    }

    public Integer getRatio() {
        return this.ratio;
    }

    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    public String getStatusValue() {
        return this.statusValue;
    }

    public void setStatusValue(String statusValue) {
        this.statusValue = statusValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserStatusInSection (");

        sb.append(userId);
        sb.append(", ").append(sectionId);
        sb.append(", ").append(ratio);
        sb.append(", ").append(statusValue);

        sb.append(")");
        return sb.toString();
    }
}
