/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserStatus implements Serializable {

    private static final long serialVersionUID = -1292377204;

    private UInteger id;
    private String statusName;
    private String description;
    private Integer lowBorder;

    public UserStatus() {
    }

    public UserStatus(UserStatus value) {
        this.id = value.id;
        this.statusName = value.statusName;
        this.description = value.description;
        this.lowBorder = value.lowBorder;
    }

    public UserStatus(
            UInteger id,
            String statusName,
            String description,
            Integer lowBorder
    ) {
        this.id = id;
        this.statusName = statusName;
        this.description = description;
        this.lowBorder = lowBorder;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getStatusName() {
        return this.statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getLowBorder() {
        return this.lowBorder;
    }

    public void setLowBorder(Integer lowBorder) {
        this.lowBorder = lowBorder;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserStatus (");

        sb.append(id);
        sb.append(", ").append(statusName);
        sb.append(", ").append(description);
        sb.append(", ").append(lowBorder);

        sb.append(")");
        return sb.toString();
    }
}
