/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserBookmark implements Serializable {

    private static final long serialVersionUID = 1433549910;

    private ULong userId;
    private ULong materialId;
    private String bookmarkName;
    private String description;
    private Object materialInnerPositionData;
    private ULong possibleCourseId;

    public UserBookmark() {
    }

    public UserBookmark(UserBookmark value) {
        this.userId = value.userId;
        this.materialId = value.materialId;
        this.bookmarkName = value.bookmarkName;
        this.description = value.description;
        this.materialInnerPositionData = value.materialInnerPositionData;
        this.possibleCourseId = value.possibleCourseId;
    }

    public UserBookmark(
            ULong userId,
            ULong materialId,
            String bookmarkName,
            String description,
            Object materialInnerPositionData,
            ULong possibleCourseId
    ) {
        this.userId = userId;
        this.materialId = materialId;
        this.bookmarkName = bookmarkName;
        this.description = description;
        this.materialInnerPositionData = materialInnerPositionData;
        this.possibleCourseId = possibleCourseId;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public ULong getMaterialId() {
        return this.materialId;
    }

    public void setMaterialId(ULong materialId) {
        this.materialId = materialId;
    }

    public String getBookmarkName() {
        return this.bookmarkName;
    }

    public void setBookmarkName(String bookmarkName) {
        this.bookmarkName = bookmarkName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Object getMaterialInnerPositionData() {
        return this.materialInnerPositionData;
    }

    public void setMaterialInnerPositionData(Object materialInnerPositionData) {
        this.materialInnerPositionData = materialInnerPositionData;
    }

    public ULong getPossibleCourseId() {
        return this.possibleCourseId;
    }

    public void setPossibleCourseId(ULong possibleCourseId) {
        this.possibleCourseId = possibleCourseId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBookmark (");

        sb.append(userId);
        sb.append(", ").append(materialId);
        sb.append(", ").append(bookmarkName);
        sb.append(", ").append(description);
        sb.append(", ").append(materialInnerPositionData);
        sb.append(", ").append(possibleCourseId);

        sb.append(")");
        return sb.toString();
    }
}
