/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.UInteger;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User implements Serializable {

    private static final long serialVersionUID = -1892006894;

    private ULong id;
    private String firstName;
    private String lastName;
    private ULong avatar;
    private String email;
    private String login;
    private String password;
    private Date registrationDate;
    private Object socialLinksJson;
    private Double ratio;
    private Boolean penalyCount;
    private UInteger statusId;

    public User() {
    }

    public User(User value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.avatar = value.avatar;
        this.email = value.email;
        this.login = value.login;
        this.password = value.password;
        this.registrationDate = value.registrationDate;
        this.socialLinksJson = value.socialLinksJson;
        this.ratio = value.ratio;
        this.penalyCount = value.penalyCount;
        this.statusId = value.statusId;
    }

    public User(
            ULong id,
            String firstName,
            String lastName,
            ULong avatar,
            String email,
            String login,
            String password,
            Date registrationDate,
            Object socialLinksJson,
            Double ratio,
            Boolean penalyCount,
            UInteger statusId
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.avatar = avatar;
        this.email = email;
        this.login = login;
        this.password = password;
        this.registrationDate = registrationDate;
        this.socialLinksJson = socialLinksJson;
        this.ratio = ratio;
        this.penalyCount = penalyCount;
        this.statusId = statusId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public ULong getAvatar() {
        return this.avatar;
    }

    public void setAvatar(ULong avatar) {
        this.avatar = avatar;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getRegistrationDate() {
        return this.registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public Object getSocialLinksJson() {
        return this.socialLinksJson;
    }

    public void setSocialLinksJson(Object socialLinksJson) {
        this.socialLinksJson = socialLinksJson;
    }

    public Double getRatio() {
        return this.ratio;
    }

    public void setRatio(Double ratio) {
        this.ratio = ratio;
    }

    public Boolean getPenalyCount() {
        return this.penalyCount;
    }

    public void setPenalyCount(Boolean penalyCount) {
        this.penalyCount = penalyCount;
    }

    public UInteger getStatusId() {
        return this.statusId;
    }

    public void setStatusId(UInteger statusId) {
        this.statusId = statusId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(avatar);
        sb.append(", ").append(email);
        sb.append(", ").append(login);
        sb.append(", ").append(password);
        sb.append(", ").append(registrationDate);
        sb.append(", ").append(socialLinksJson);
        sb.append(", ").append(ratio);
        sb.append(", ").append(penalyCount);
        sb.append(", ").append(statusId);

        sb.append(")");
        return sb.toString();
    }
}
