/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserSavedAttachment implements Serializable {

    private static final long serialVersionUID = -790385458;

    private ULong userId;
    private ULong attachmentObjectStorageFileId;

    public UserSavedAttachment() {
    }

    public UserSavedAttachment(UserSavedAttachment value) {
        this.userId = value.userId;
        this.attachmentObjectStorageFileId = value.attachmentObjectStorageFileId;
    }

    public UserSavedAttachment(
            ULong userId,
            ULong attachmentObjectStorageFileId
    ) {
        this.userId = userId;
        this.attachmentObjectStorageFileId = attachmentObjectStorageFileId;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public ULong getAttachmentObjectStorageFileId() {
        return this.attachmentObjectStorageFileId;
    }

    public void setAttachmentObjectStorageFileId(ULong attachmentObjectStorageFileId) {
        this.attachmentObjectStorageFileId = attachmentObjectStorageFileId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSavedAttachment (");

        sb.append(userId);
        sb.append(", ").append(attachmentObjectStorageFileId);

        sb.append(")");
        return sb.toString();
    }
}
