/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.jooq.types.UShort;
import ua.ddovgal.brainshareApi.jooq.tables.TCourse;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RCourseRecord extends UpdatableRecordImpl<RCourseRecord> implements Record6<ULong, String, ULong, UShort, String, UInteger> {

    private static final long serialVersionUID = -1478077401;

    /**
     * Create a detached RCourseRecord
     */
    public RCourseRecord() {
        super(TCourse.COURSE);
    }

    /**
     * Create a detached, initialised RCourseRecord
     */
    public RCourseRecord(ULong id, String name, ULong creatorUserId, UShort materialsInsideCount, String description, UInteger sectionId) {
        super(TCourse.COURSE);

        set(0, id);
        set(1, name);
        set(2, creatorUserId);
        set(3, materialsInsideCount);
        set(4, description);
        set(5, sectionId);
    }

    /**
     * Getter for <code>brainshare_dev.course.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.course.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.course.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.course.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.course.creator_user_id</code>.
     */
    public ULong getCreatorUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.course.creator_user_id</code>.
     */
    public void setCreatorUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>brainshare_dev.course.materials_inside_count</code>.
     */
    public UShort getMaterialsInsideCount() {
        return (UShort) get(3);
    }

    /**
     * Setter for <code>brainshare_dev.course.materials_inside_count</code>.
     */
    public void setMaterialsInsideCount(UShort value) {
        set(3, value);
    }

    /**
     * Getter for <code>brainshare_dev.course.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>brainshare_dev.course.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.course.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.course.section_id</code>.
     */
    public void setSectionId(UInteger value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, String, ULong, UShort, String, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, String, ULong, UShort, String, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TCourse.COURSE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TCourse.COURSE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return TCourse.COURSE.CREATOR_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field4() {
        return TCourse.COURSE.MATERIALS_INSIDE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TCourse.COURSE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return TCourse.COURSE.SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getCreatorUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value4() {
        return getMaterialsInsideCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value3(ULong value) {
        setCreatorUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value4(UShort value) {
        setMaterialsInsideCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value5(String value) {
        setDescription(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord value6(UInteger value) {
        setSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RCourseRecord values(ULong value1, String value2, ULong value3, UShort value4, String value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
