/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TMaterialRecommendation;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RMaterialRecommendationRecord extends UpdatableRecordImpl<RMaterialRecommendationRecord> implements Record3<ULong, ULong, String> {

    private static final long serialVersionUID = 1583646345;

    /**
     * Create a detached RMaterialRecommendationRecord
     */
    public RMaterialRecommendationRecord() {
        super(TMaterialRecommendation.MATERIAL_RECOMMENDATION);
    }

    /**
     * Create a detached, initialised RMaterialRecommendationRecord
     */
    public RMaterialRecommendationRecord(ULong sourceMaterialId, ULong recommendedMaterialId, String recommendationType) {
        super(TMaterialRecommendation.MATERIAL_RECOMMENDATION);

        set(0, sourceMaterialId);
        set(1, recommendedMaterialId);
        set(2, recommendationType);
    }

    /**
     * Getter for <code>brainshare_dev.material_recommendation.source_material_id</code>.
     */
    public ULong getSourceMaterialId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.material_recommendation.source_material_id</code>.
     */
    public void setSourceMaterialId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.material_recommendation.recommended_material_id</code>.
     */
    public ULong getRecommendedMaterialId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.material_recommendation.recommended_material_id</code>.
     */
    public void setRecommendedMaterialId(ULong value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.material_recommendation.recommendation_type</code>.
     */
    public String getRecommendationType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.material_recommendation.recommendation_type</code>.
     */
    public void setRecommendationType(String value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TMaterialRecommendation.MATERIAL_RECOMMENDATION.SOURCE_MATERIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TMaterialRecommendation.MATERIAL_RECOMMENDATION.RECOMMENDED_MATERIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TMaterialRecommendation.MATERIAL_RECOMMENDATION.RECOMMENDATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getSourceMaterialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getRecommendedMaterialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRecommendationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecommendationRecord value1(ULong value) {
        setSourceMaterialId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecommendationRecord value2(ULong value) {
        setRecommendedMaterialId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecommendationRecord value3(String value) {
        setRecommendationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecommendationRecord values(ULong value1, ULong value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
