/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TMaterial;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RMaterialRecord extends UpdatableRecordImpl<RMaterialRecord> implements Record17<ULong, String, ULong, Integer, Byte, UInteger, UInteger, UInteger, UInteger, Timestamp, UInteger, ULong, UInteger, String, Object, ULong, UInteger> {

    private static final long serialVersionUID = -1049953874;

    /**
     * Create a detached RMaterialRecord
     */
    public RMaterialRecord() {
        super(TMaterial.MATERIAL);
    }

    /**
     * Create a detached, initialised RMaterialRecord
     */
    public RMaterialRecord(ULong id, String title, ULong authorUserId, Integer ratio, Byte hasLowPriority, UInteger positiveMarkCount, UInteger negativeMarkCount, UInteger stateId, UInteger approvalValue, Timestamp creationDatetime, UInteger formatId, ULong courseId, UInteger sectionId, String tagsSeparatedByComma, Object previewContentDataJson, ULong contentDataId, UInteger viewCount) {
        super(TMaterial.MATERIAL);

        set(0, id);
        set(1, title);
        set(2, authorUserId);
        set(3, ratio);
        set(4, hasLowPriority);
        set(5, positiveMarkCount);
        set(6, negativeMarkCount);
        set(7, stateId);
        set(8, approvalValue);
        set(9, creationDatetime);
        set(10, formatId);
        set(11, courseId);
        set(12, sectionId);
        set(13, tagsSeparatedByComma);
        set(14, previewContentDataJson);
        set(15, contentDataId);
        set(16, viewCount);
    }

    /**
     * Getter for <code>brainshare_dev.material.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.material.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.material.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.author_user_id</code>.
     */
    public ULong getAuthorUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.material.author_user_id</code>.
     */
    public void setAuthorUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.ratio</code>.
     */
    public Integer getRatio() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>brainshare_dev.material.ratio</code>.
     */
    public void setRatio(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.has_low_priority</code>.
     */
    public Byte getHasLowPriority() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>brainshare_dev.material.has_low_priority</code>.
     */
    public void setHasLowPriority(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.positive_mark_count</code>.
     */
    public UInteger getPositiveMarkCount() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>brainshare_dev.material.positive_mark_count</code>.
     */
    public void setPositiveMarkCount(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.negative_mark_count</code>.
     */
    public UInteger getNegativeMarkCount() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>brainshare_dev.material.negative_mark_count</code>.
     */
    public void setNegativeMarkCount(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.state_id</code>.
     */
    public UInteger getStateId() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>brainshare_dev.material.state_id</code>.
     */
    public void setStateId(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.approval_value</code>.
     */
    public UInteger getApprovalValue() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>brainshare_dev.material.approval_value</code>.
     */
    public void setApprovalValue(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.creation_datetime</code>.
     */
    public Timestamp getCreationDatetime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>brainshare_dev.material.creation_datetime</code>.
     */
    public void setCreationDatetime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.format_id</code>.
     */
    public UInteger getFormatId() {
        return (UInteger) get(10);
    }

    /**
     * Setter for <code>brainshare_dev.material.format_id</code>.
     */
    public void setFormatId(UInteger value) {
        set(10, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.course_id</code>.
     */
    public ULong getCourseId() {
        return (ULong) get(11);
    }

    /**
     * Setter for <code>brainshare_dev.material.course_id</code>.
     */
    public void setCourseId(ULong value) {
        set(11, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(12);
    }

    /**
     * Setter for <code>brainshare_dev.material.section_id</code>.
     */
    public void setSectionId(UInteger value) {
        set(12, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.tags_separated_by_comma</code>.
     */
    public String getTagsSeparatedByComma() {
        return (String) get(13);
    }

    /**
     * Setter for <code>brainshare_dev.material.tags_separated_by_comma</code>.
     */
    public void setTagsSeparatedByComma(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.preview_content_data_json</code>.
     */
    public Object getPreviewContentDataJson() {
        return (Object) get(14);
    }

    /**
     * Setter for <code>brainshare_dev.material.preview_content_data_json</code>.
     */
    public void setPreviewContentDataJson(Object value) {
        set(14, value);
    }

    /**
     * Getter for <code>brainshare_dev.material.content_data_id</code>.
     */
    public ULong getContentDataId() {
        return (ULong) get(15);
    }

    /**
     * Setter for <code>brainshare_dev.material.content_data_id</code>.
     */
    public void setContentDataId(ULong value) {
        set(15, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.material.view_count</code>.
     */
    public UInteger getViewCount() {
        return (UInteger) get(16);
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.material.view_count</code>.
     */
    public void setViewCount(UInteger value) {
        set(16, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<ULong, String, ULong, Integer, Byte, UInteger, UInteger, UInteger, UInteger, Timestamp, UInteger, ULong, UInteger, String, Object, ULong, UInteger> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<ULong, String, ULong, Integer, Byte, UInteger, UInteger, UInteger, UInteger, Timestamp, UInteger, ULong, UInteger, String, Object, ULong, UInteger> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TMaterial.MATERIAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TMaterial.MATERIAL.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return TMaterial.MATERIAL.AUTHOR_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TMaterial.MATERIAL.RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TMaterial.MATERIAL.HAS_LOW_PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return TMaterial.MATERIAL.POSITIVE_MARK_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return TMaterial.MATERIAL.NEGATIVE_MARK_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return TMaterial.MATERIAL.STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return TMaterial.MATERIAL.APPROVAL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TMaterial.MATERIAL.CREATION_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field11() {
        return TMaterial.MATERIAL.FORMAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field12() {
        return TMaterial.MATERIAL.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field13() {
        return TMaterial.MATERIAL.SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TMaterial.MATERIAL.TAGS_SEPARATED_BY_COMMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field15() {
        return TMaterial.MATERIAL.PREVIEW_CONTENT_DATA_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field16() {
        return TMaterial.MATERIAL.CONTENT_DATA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field17() {
        return TMaterial.MATERIAL.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getAuthorUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getHasLowPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getPositiveMarkCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getNegativeMarkCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getApprovalValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreationDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value11() {
        return getFormatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value12() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value13() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getTagsSeparatedByComma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value15() {
        return getPreviewContentDataJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value16() {
        return getContentDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value17() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value3(ULong value) {
        setAuthorUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value4(Integer value) {
        setRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value5(Byte value) {
        setHasLowPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value6(UInteger value) {
        setPositiveMarkCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value7(UInteger value) {
        setNegativeMarkCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value8(UInteger value) {
        setStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value9(UInteger value) {
        setApprovalValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value10(Timestamp value) {
        setCreationDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value11(UInteger value) {
        setFormatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value12(ULong value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value13(UInteger value) {
        setSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value14(String value) {
        setTagsSeparatedByComma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value15(Object value) {
        setPreviewContentDataJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value16(ULong value) {
        setContentDataId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord value17(UInteger value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialRecord values(ULong value1, String value2, ULong value3, Integer value4, Byte value5, UInteger value6, UInteger value7, UInteger value8, UInteger value9, Timestamp value10, UInteger value11, ULong value12, UInteger value13, String value14, Object value15, ULong value16, UInteger value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }
}
