/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TMaterialAttachment;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RMaterialAttachmentRecord extends UpdatableRecordImpl<RMaterialAttachmentRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = -213743608;

    /**
     * Create a detached RMaterialAttachmentRecord
     */
    public RMaterialAttachmentRecord() {
        super(TMaterialAttachment.MATERIAL_ATTACHMENT);
    }

    /**
     * Create a detached, initialised RMaterialAttachmentRecord
     */
    public RMaterialAttachmentRecord(ULong materialId, ULong objectStorageFileId) {
        super(TMaterialAttachment.MATERIAL_ATTACHMENT);

        set(0, materialId);
        set(1, objectStorageFileId);
    }

    /**
     * Getter for <code>brainshare_dev.material_attachment.material_id</code>.
     */
    public ULong getMaterialId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.material_attachment.material_id</code>.
     */
    public void setMaterialId(ULong value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.material_attachment.object_storage_file_id</code>.
     */
    public ULong getObjectStorageFileId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.material_attachment.object_storage_file_id</code>.
     */
    public void setObjectStorageFileId(ULong value) {
        set(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TMaterialAttachment.MATERIAL_ATTACHMENT.MATERIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TMaterialAttachment.MATERIAL_ATTACHMENT.OBJECT_STORAGE_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getMaterialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getObjectStorageFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialAttachmentRecord value1(ULong value) {
        setMaterialId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialAttachmentRecord value2(ULong value) {
        setObjectStorageFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialAttachmentRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
