/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TMaterialMark;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RMaterialMarkRecord extends UpdatableRecordImpl<RMaterialMarkRecord> implements Record3<ULong, ULong, Byte> {

    private static final long serialVersionUID = -1736452462;

    /**
     * Create a detached RMaterialMarkRecord
     */
    public RMaterialMarkRecord() {
        super(TMaterialMark.MATERIAL_MARK);
    }

    /**
     * Create a detached, initialised RMaterialMarkRecord
     */
    public RMaterialMarkRecord(ULong materialId, ULong setterUserId, Byte isUpMark) {
        super(TMaterialMark.MATERIAL_MARK);

        set(0, materialId);
        set(1, setterUserId);
        set(2, isUpMark);
    }

    /**
     * Getter for <code>brainshare_dev.material_mark.material_id</code>.
     */
    public ULong getMaterialId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.material_mark.material_id</code>.
     */
    public void setMaterialId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.material_mark.setter_user_id</code>.
     */
    public ULong getSetterUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.material_mark.setter_user_id</code>.
     */
    public void setSetterUserId(ULong value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.material_mark.is_up_mark</code>.
     */
    public Byte getIsUpMark() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.material_mark.is_up_mark</code>.
     */
    public void setIsUpMark(Byte value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TMaterialMark.MATERIAL_MARK.MATERIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TMaterialMark.MATERIAL_MARK.SETTER_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TMaterialMark.MATERIAL_MARK.IS_UP_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getMaterialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getSetterUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIsUpMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialMarkRecord value1(ULong value) {
        setMaterialId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialMarkRecord value2(ULong value) {
        setSetterUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialMarkRecord value3(Byte value) {
        setIsUpMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RMaterialMarkRecord values(ULong value1, ULong value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
