/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TNotificationAboutSubcomment;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RNotificationAboutSubcommentRecord extends UpdatableRecordImpl<RNotificationAboutSubcommentRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = -327649442;

    /**
     * Create a detached RNotificationAboutSubcommentRecord
     */
    public RNotificationAboutSubcommentRecord() {
        super(TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT);
    }

    /**
     * Create a detached, initialised RNotificationAboutSubcommentRecord
     */
    public RNotificationAboutSubcommentRecord(ULong notificationId, ULong reasonId) {
        super(TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT);

        set(0, notificationId);
        set(1, reasonId);
    }

    /**
     * Getter for <code>brainshare_dev.notification_about_subcomment.notification_id</code>.
     */
    public ULong getNotificationId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.notification_about_subcomment.notification_id</code>.
     */
    public void setNotificationId(ULong value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.notification_about_subcomment.reason_id</code>.
     */
    public ULong getReasonId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.notification_about_subcomment.reason_id</code>.
     */
    public void setReasonId(ULong value) {
        set(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT.NOTIFICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TNotificationAboutSubcomment.NOTIFICATION_ABOUT_SUBCOMMENT.REASON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getNotificationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getReasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RNotificationAboutSubcommentRecord value1(ULong value) {
        setNotificationId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RNotificationAboutSubcommentRecord value2(ULong value) {
        setReasonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RNotificationAboutSubcommentRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
