/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TObjectStorageFile;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RObjectStorageFileRecord extends UpdatableRecordImpl<RObjectStorageFileRecord> implements Record3<ULong, String, String> {

    private static final long serialVersionUID = -1114821140;

    /**
     * Create a detached RObjectStorageFileRecord
     */
    public RObjectStorageFileRecord() {
        super(TObjectStorageFile.OBJECT_STORAGE_FILE);
    }

    /**
     * Create a detached, initialised RObjectStorageFileRecord
     */
    public RObjectStorageFileRecord(ULong id, String bucket, String inBucketFileId) {
        super(TObjectStorageFile.OBJECT_STORAGE_FILE);

        set(0, id);
        set(1, bucket);
        set(2, inBucketFileId);
    }

    /**
     * Getter for <code>brainshare_dev.object_storage_file.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.object_storage_file.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.object_storage_file.bucket</code>.
     */
    public String getBucket() {
        return (String) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.object_storage_file.bucket</code>.
     */
    public void setBucket(String value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.object_storage_file.in_bucket_file_id</code>.
     */
    public String getInBucketFileId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.object_storage_file.in_bucket_file_id</code>.
     */
    public void setInBucketFileId(String value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TObjectStorageFile.OBJECT_STORAGE_FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TObjectStorageFile.OBJECT_STORAGE_FILE.BUCKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TObjectStorageFile.OBJECT_STORAGE_FILE.IN_BUCKET_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBucket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInBucketFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RObjectStorageFileRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RObjectStorageFileRecord value2(String value) {
        setBucket(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RObjectStorageFileRecord value3(String value) {
        setInBucketFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RObjectStorageFileRecord values(ULong value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
