/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import ua.ddovgal.brainshareApi.jooq.tables.TSection;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RSectionRecord extends UpdatableRecordImpl<RSectionRecord> implements Record4<UInteger, UInteger, String, String> {

    private static final long serialVersionUID = -1434799551;

    /**
     * Create a detached RSectionRecord
     */
    public RSectionRecord() {
        super(TSection.SECTION);
    }

    /**
     * Create a detached, initialised RSectionRecord
     */
    public RSectionRecord(UInteger id, UInteger superSectionId, String sectionName, String description) {
        super(TSection.SECTION);

        set(0, id);
        set(1, superSectionId);
        set(2, sectionName);
        set(3, description);
    }

    /**
     * Getter for <code>brainshare_dev.section.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.section.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.section.super_section_id</code>.
     */
    public UInteger getSuperSectionId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.section.super_section_id</code>.
     */
    public void setSuperSectionId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.section.section_name</code>.
     */
    public String getSectionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.section.section_name</code>.
     */
    public void setSectionName(String value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.section.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.section.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TSection.SECTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TSection.SECTION.SUPER_SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TSection.SECTION.SECTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TSection.SECTION.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSuperSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSectionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RSectionRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RSectionRecord value2(UInteger value) {
        setSuperSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RSectionRecord value3(String value) {
        setSectionName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RSectionRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RSectionRecord values(UInteger value1, UInteger value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
