/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TUserDesirableSection;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserDesirableSectionRecord extends UpdatableRecordImpl<RUserDesirableSectionRecord> implements Record2<ULong, UInteger> {

    private static final long serialVersionUID = 132128226;

    /**
     * Create a detached RUserDesirableSectionRecord
     */
    public RUserDesirableSectionRecord() {
        super(TUserDesirableSection.USER_DESIRABLE_SECTION);
    }

    /**
     * Create a detached, initialised RUserDesirableSectionRecord
     */
    public RUserDesirableSectionRecord(ULong userId, UInteger sectionId) {
        super(TUserDesirableSection.USER_DESIRABLE_SECTION);

        set(0, userId);
        set(1, sectionId);
    }

    /**
     * Getter for <code>brainshare_dev.user_desirable_section.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user_desirable_section.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user_desirable_section.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user_desirable_section.section_id</code>.
     */
    public void setSectionId(UInteger value) {
        set(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, UInteger> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, UInteger> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, UInteger> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TUserDesirableSection.USER_DESIRABLE_SECTION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TUserDesirableSection.USER_DESIRABLE_SECTION.SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserDesirableSectionRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserDesirableSectionRecord value2(UInteger value) {
        setSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserDesirableSectionRecord values(ULong value1, UInteger value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
