/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TUserSavedAttachment;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserSavedAttachmentRecord extends UpdatableRecordImpl<RUserSavedAttachmentRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = -513322434;

    /**
     * Create a detached RUserSavedAttachmentRecord
     */
    public RUserSavedAttachmentRecord() {
        super(TUserSavedAttachment.USER_SAVED_ATTACHMENT);
    }

    /**
     * Create a detached, initialised RUserSavedAttachmentRecord
     */
    public RUserSavedAttachmentRecord(ULong userId, ULong attachmentObjectStorageFileId) {
        super(TUserSavedAttachment.USER_SAVED_ATTACHMENT);

        set(0, userId);
        set(1, attachmentObjectStorageFileId);
    }

    /**
     * Getter for <code>brainshare_dev.user_saved_attachment.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user_saved_attachment.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user_saved_attachment.attachment_object_storage_file_id</code>.
     */
    public ULong getAttachmentObjectStorageFileId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user_saved_attachment.attachment_object_storage_file_id</code>.
     */
    public void setAttachmentObjectStorageFileId(ULong value) {
        set(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TUserSavedAttachment.USER_SAVED_ATTACHMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TUserSavedAttachment.USER_SAVED_ATTACHMENT.ATTACHMENT_OBJECT_STORAGE_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getAttachmentObjectStorageFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserSavedAttachmentRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserSavedAttachmentRecord value2(ULong value) {
        setAttachmentObjectStorageFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserSavedAttachmentRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
