/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TUser;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserRecord extends UpdatableRecordImpl<RUserRecord> implements Record12<ULong, String, String, ULong, String, String, String, Date, Object, Double, Boolean, UInteger> {

    private static final long serialVersionUID = 597742701;

    /**
     * Create a detached RUserRecord
     */
    public RUserRecord() {
        super(TUser.USER);
    }

    /**
     * Create a detached, initialised RUserRecord
     */
    public RUserRecord(ULong id, String firstName, String lastName, ULong avatar, String email, String login, String password, Date registrationDate, Object socialLinksJson, Double ratio, Boolean penalyCount, UInteger statusId) {
        super(TUser.USER);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
        set(3, avatar);
        set(4, email);
        set(5, login);
        set(6, password);
        set(7, registrationDate);
        set(8, socialLinksJson);
        set(9, ratio);
        set(10, penalyCount);
        set(11, statusId);
    }

    /**
     * Getter for <code>brainshare_dev.user.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.user.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.avatar</code>.
     */
    public ULong getAvatar() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>brainshare_dev.user.avatar</code>.
     */
    public void setAvatar(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>brainshare_dev.user.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.login</code>.
     */
    public String getLogin() {
        return (String) get(5);
    }

    /**
     * Setter for <code>brainshare_dev.user.login</code>.
     */
    public void setLogin(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>brainshare_dev.user.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.registration_date</code>.
     */
    public Date getRegistrationDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>brainshare_dev.user.registration_date</code>.
     */
    public void setRegistrationDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.social_links_json</code>.
     */
    public Object getSocialLinksJson() {
        return (Object) get(8);
    }

    /**
     * Setter for <code>brainshare_dev.user.social_links_json</code>.
     */
    public void setSocialLinksJson(Object value) {
        set(8, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.ratio</code>.
     */
    public Double getRatio() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>brainshare_dev.user.ratio</code>.
     */
    public void setRatio(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>brainshare_dev.user.penaly_count</code>.
     */
    public Boolean getPenalyCount() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>brainshare_dev.user.penaly_count</code>.
     */
    public void setPenalyCount(Boolean value) {
        set(10, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user.status_id</code>.
     */
    public UInteger getStatusId() {
        return (UInteger) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user.status_id</code>.
     */
    public void setStatusId(UInteger value) {
        set(11, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, String, String, ULong, String, String, String, Date, Object, Double, Boolean, UInteger> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, String, String, ULong, String, String, String, Date, Object, Double, Boolean, UInteger> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TUser.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUser.USER.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUser.USER.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return TUser.USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TUser.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TUser.USER.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TUser.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return TUser.USER.REGISTRATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field9() {
        return TUser.USER.SOCIAL_LINKS_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return TUser.USER.RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return TUser.USER.PENALY_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field12() {
        return TUser.USER.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getRegistrationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value9() {
        return getSocialLinksJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getPenalyCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value12() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value3(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value4(ULong value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value6(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value7(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value8(Date value) {
        setRegistrationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value9(Object value) {
        setSocialLinksJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value10(Double value) {
        setRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value11(Boolean value) {
        setPenalyCount(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord value12(UInteger value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserRecord values(ULong value1, String value2, String value3, ULong value4, String value5, String value6, String value7, Date value8, Object value9, Double value10, Boolean value11, UInteger value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }
}
