/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TUserBookmark;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserBookmarkRecord extends UpdatableRecordImpl<RUserBookmarkRecord> implements Record6<ULong, ULong, String, String, Object, ULong> {

    private static final long serialVersionUID = 1274836299;

    /**
     * Create a detached RUserBookmarkRecord
     */
    public RUserBookmarkRecord() {
        super(TUserBookmark.USER_BOOKMARK);
    }

    /**
     * Create a detached, initialised RUserBookmarkRecord
     */
    public RUserBookmarkRecord(ULong userId, ULong materialId, String bookmarkName, String description, Object materialInnerPositionData, ULong possibleCourseId) {
        super(TUserBookmark.USER_BOOKMARK);

        set(0, userId);
        set(1, materialId);
        set(2, bookmarkName);
        set(3, description);
        set(4, materialInnerPositionData);
        set(5, possibleCourseId);
    }

    /**
     * Getter for <code>brainshare_dev.user_bookmark.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user_bookmark.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_bookmark.material_id</code>.
     */
    public ULong getMaterialId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.user_bookmark.material_id</code>.
     */
    public void setMaterialId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_bookmark.bookmark_name</code>.
     */
    public String getBookmarkName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.user_bookmark.bookmark_name</code>.
     */
    public void setBookmarkName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_bookmark.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>brainshare_dev.user_bookmark.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_bookmark.material_inner_position_data</code>.
     */
    public Object getMaterialInnerPositionData() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>brainshare_dev.user_bookmark.material_inner_position_data</code>.
     */
    public void setMaterialInnerPositionData(Object value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user_bookmark.possible_course_id</code>.
     */
    public ULong getPossibleCourseId() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user_bookmark.possible_course_id</code>.
     */
    public void setPossibleCourseId(ULong value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, String, String, Object, ULong> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, String, String, Object, ULong> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TUserBookmark.USER_BOOKMARK.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TUserBookmark.USER_BOOKMARK.MATERIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUserBookmark.USER_BOOKMARK.BOOKMARK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUserBookmark.USER_BOOKMARK.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return TUserBookmark.USER_BOOKMARK.MATERIAL_INNER_POSITION_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return TUserBookmark.USER_BOOKMARK.POSSIBLE_COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getMaterialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBookmarkName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return getMaterialInnerPositionData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getPossibleCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value2(ULong value) {
        setMaterialId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value3(String value) {
        setBookmarkName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value5(Object value) {
        setMaterialInnerPositionData(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord value6(ULong value) {
        setPossibleCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserBookmarkRecord values(ULong value1, ULong value2, String value3, String value4, Object value5, ULong value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
