/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import ua.ddovgal.brainshareApi.jooq.tables.TUserStatus;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserStatusRecord extends UpdatableRecordImpl<RUserStatusRecord> implements Record4<UInteger, String, String, Integer> {

    private static final long serialVersionUID = 1591639315;

    /**
     * Create a detached RUserStatusRecord
     */
    public RUserStatusRecord() {
        super(TUserStatus.USER_STATUS);
    }

    /**
     * Create a detached, initialised RUserStatusRecord
     */
    public RUserStatusRecord(UInteger id, String statusName, String description, Integer lowBorder) {
        super(TUserStatus.USER_STATUS);

        set(0, id);
        set(1, statusName);
        set(2, description);
        set(3, lowBorder);
    }

    /**
     * Getter for <code>brainshare_dev.user_status.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user_status.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_status.status_name</code>.
     */
    public String getStatusName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.user_status.status_name</code>.
     */
    public void setStatusName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_status.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.user_status.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user_status.low_border</code>.
     */
    public Integer getLowBorder() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user_status.low_border</code>.
     */
    public void setLowBorder(Integer value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TUserStatus.USER_STATUS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUserStatus.USER_STATUS.STATUS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUserStatus.USER_STATUS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TUserStatus.USER_STATUS.LOW_BORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatusName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLowBorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusRecord value2(String value) {
        setStatusName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusRecord value3(String value) {
        setDescription(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusRecord value4(Integer value) {
        setLowBorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusRecord values(UInteger value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
