/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.tables.TUserStatusInSection;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RUserStatusInSectionRecord extends UpdatableRecordImpl<RUserStatusInSectionRecord> implements Record4<ULong, UInteger, Integer, String> {

    private static final long serialVersionUID = -2116864567;

    /**
     * Create a detached RUserStatusInSectionRecord
     */
    public RUserStatusInSectionRecord() {
        super(TUserStatusInSection.USER_STATUS_IN_SECTION);
    }

    /**
     * Create a detached, initialised RUserStatusInSectionRecord
     */
    public RUserStatusInSectionRecord(ULong userId, UInteger sectionId, Integer ratio, String statusValue) {
        super(TUserStatusInSection.USER_STATUS_IN_SECTION);

        set(0, userId);
        set(1, sectionId);
        set(2, ratio);
        set(3, statusValue);
    }

    /**
     * Getter for <code>brainshare_dev.user_status_in_section.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>brainshare_dev.user_status_in_section.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_status_in_section.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>brainshare_dev.user_status_in_section.section_id</code>.
     */
    public void setSectionId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>brainshare_dev.user_status_in_section.ratio</code>.
     */
    public Integer getRatio() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>brainshare_dev.user_status_in_section.ratio</code>.
     */
    public void setRatio(Integer value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>brainshare_dev.user_status_in_section.status_value</code>.
     */
    public String getStatusValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>brainshare_dev.user_status_in_section.status_value</code>.
     */
    public void setStatusValue(String value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, UInteger> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, UInteger, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, UInteger, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TUserStatusInSection.USER_STATUS_IN_SECTION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TUserStatusInSection.USER_STATUS_IN_SECTION.SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TUserStatusInSection.USER_STATUS_IN_SECTION.RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUserStatusInSection.USER_STATUS_IN_SECTION.STATUS_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatusValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusInSectionRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusInSectionRecord value2(UInteger value) {
        setSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusInSectionRecord value3(Integer value) {
        setRatio(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusInSectionRecord value4(String value) {
        setStatusValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserStatusInSectionRecord values(ULong value1, UInteger value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
