/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RMaterialRecommendationRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TMaterialRecommendation extends TableImpl<RMaterialRecommendationRecord> {

    /**
     * The reference instance of <code>brainshare_dev.material_recommendation</code>
     */
    public static final TMaterialRecommendation MATERIAL_RECOMMENDATION = new TMaterialRecommendation();
    private static final long serialVersionUID = 1624251265;
    /**
     * The column <code>brainshare_dev.material_recommendation.source_material_id</code>.
     */
    public final TableField<RMaterialRecommendationRecord, ULong> SOURCE_MATERIAL_ID = createField("source_material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_recommendation.recommended_material_id</code>.
     */
    public final TableField<RMaterialRecommendationRecord, ULong> RECOMMENDED_MATERIAL_ID = createField("recommended_material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_recommendation.recommendation_type</code>.
     */
    public final TableField<RMaterialRecommendationRecord, String> RECOMMENDATION_TYPE = createField("recommendation_type", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.material_recommendation</code> table reference
     */
    public TMaterialRecommendation() {
        this("material_recommendation", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.material_recommendation</code> table reference
     */
    public TMaterialRecommendation(String alias) {
        this(alias, MATERIAL_RECOMMENDATION);
    }

    private TMaterialRecommendation(String alias, Table<RMaterialRecommendationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMaterialRecommendation(String alias, Table<RMaterialRecommendationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RMaterialRecommendationRecord> getRecordType() {
        return RMaterialRecommendationRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RMaterialRecommendationRecord> getPrimaryKey() {
        return Keys.KEY_MATERIAL_RECOMMENDATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RMaterialRecommendationRecord>> getKeys() {
        return Arrays.<UniqueKey<RMaterialRecommendationRecord>>asList(Keys.KEY_MATERIAL_RECOMMENDATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RMaterialRecommendationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RMaterialRecommendationRecord, ?>>asList(Keys.FK_MATERIAL_RECOMMENDATION_SOURCE_MATERIAL_ID, Keys.FK_MATERIAL_RECOMMENDATION_RECOMMENDED_MATERIAL_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMaterialRecommendation as(String alias) {
        return new TMaterialRecommendation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMaterialRecommendation rename(String name) {
        return new TMaterialRecommendation(name, null);
    }
}
