/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RMaterialStateRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TMaterialState extends TableImpl<RMaterialStateRecord> {

    /**
     * The reference instance of <code>brainshare_dev.material_state</code>
     */
    public static final TMaterialState MATERIAL_STATE = new TMaterialState();
    private static final long serialVersionUID = -149495220;
    /**
     * The column <code>brainshare_dev.material_state.id</code>.
     */
    public final TableField<RMaterialStateRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_state.state_name</code>.
     */
    public final TableField<RMaterialStateRecord, String> STATE_NAME = createField("state_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_state.description</code>.
     */
    public final TableField<RMaterialStateRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_state.low_border</code>.
     */
    public final TableField<RMaterialStateRecord, Integer> LOW_BORDER = createField("low_border", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.material_state</code> table reference
     */
    public TMaterialState() {
        this("material_state", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.material_state</code> table reference
     */
    public TMaterialState(String alias) {
        this(alias, MATERIAL_STATE);
    }

    private TMaterialState(String alias, Table<RMaterialStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMaterialState(String alias, Table<RMaterialStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RMaterialStateRecord> getRecordType() {
        return RMaterialStateRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RMaterialStateRecord> getPrimaryKey() {
        return Keys.KEY_MATERIAL_STATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RMaterialStateRecord>> getKeys() {
        return Arrays.<UniqueKey<RMaterialStateRecord>>asList(Keys.KEY_MATERIAL_STATE_PRIMARY, Keys.KEY_MATERIAL_STATE_STATE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMaterialState as(String alias) {
        return new TMaterialState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMaterialState rename(String name) {
        return new TMaterialState(name, null);
    }
}
