/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RMaterialAttachmentRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TMaterialAttachment extends TableImpl<RMaterialAttachmentRecord> {

    /**
     * The reference instance of <code>brainshare_dev.material_attachment</code>
     */
    public static final TMaterialAttachment MATERIAL_ATTACHMENT = new TMaterialAttachment();
    private static final long serialVersionUID = 106621590;
    /**
     * The column <code>brainshare_dev.material_attachment.material_id</code>.
     */
    public final TableField<RMaterialAttachmentRecord, ULong> MATERIAL_ID = createField("material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.material_attachment.object_storage_file_id</code>.
     */
    public final TableField<RMaterialAttachmentRecord, ULong> OBJECT_STORAGE_FILE_ID = createField("object_storage_file_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.material_attachment</code> table reference
     */
    public TMaterialAttachment() {
        this("material_attachment", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.material_attachment</code> table reference
     */
    public TMaterialAttachment(String alias) {
        this(alias, MATERIAL_ATTACHMENT);
    }

    private TMaterialAttachment(String alias, Table<RMaterialAttachmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMaterialAttachment(String alias, Table<RMaterialAttachmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RMaterialAttachmentRecord> getRecordType() {
        return RMaterialAttachmentRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RMaterialAttachmentRecord> getPrimaryKey() {
        return Keys.KEY_MATERIAL_ATTACHMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RMaterialAttachmentRecord>> getKeys() {
        return Arrays.<UniqueKey<RMaterialAttachmentRecord>>asList(Keys.KEY_MATERIAL_ATTACHMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RMaterialAttachmentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RMaterialAttachmentRecord, ?>>asList(Keys.FK_MATERIAL_ATTACHMENT_MATERIAL_ID, Keys.FK_MATERIAL_ATTACHMENT_OBJECT_STORAGE_FILE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMaterialAttachment as(String alias) {
        return new TMaterialAttachment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMaterialAttachment rename(String name) {
        return new TMaterialAttachment(name, null);
    }
}
