/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RModificationRecord;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TModification extends TableImpl<RModificationRecord> {

    /**
     * The reference instance of <code>brainshare_dev.modification</code>
     */
    public static final TModification MODIFICATION = new TModification();
    private static final long serialVersionUID = 878018213;
    /**
     * The column <code>brainshare_dev.modification.id</code>.
     */
    public final TableField<RModificationRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.modification.source_material_id</code>.
     */
    public final TableField<RModificationRecord, ULong> SOURCE_MATERIAL_ID = createField("source_material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.modification.requester_user_id</code>.
     */
    public final TableField<RModificationRecord, ULong> REQUESTER_USER_ID = createField("requester_user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.modification.modification_data_json</code>.
     */
    public final TableField<RModificationRecord, Object> MODIFICATION_DATA_JSON = createField("modification_data_json", org.jooq.impl.DefaultDataType.getDefaultDataType("json"), this, "");
    /**
     * The column <code>brainshare_dev.modification.is_accepted</code>.
     */
    public final TableField<RModificationRecord, Byte> IS_ACCEPTED = createField("is_accepted", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.modification.creation_datetime</code>.
     */
    public final TableField<RModificationRecord, Timestamp> CREATION_DATETIME = createField("creation_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.modification</code> table reference
     */
    public TModification() {
        this("modification", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.modification</code> table reference
     */
    public TModification(String alias) {
        this(alias, MODIFICATION);
    }

    private TModification(String alias, Table<RModificationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TModification(String alias, Table<RModificationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RModificationRecord> getRecordType() {
        return RModificationRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RModificationRecord, ULong> getIdentity() {
        return Keys.IDENTITY_MODIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RModificationRecord> getPrimaryKey() {
        return Keys.KEY_MODIFICATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RModificationRecord>> getKeys() {
        return Arrays.<UniqueKey<RModificationRecord>>asList(Keys.KEY_MODIFICATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RModificationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RModificationRecord, ?>>asList(Keys.FK_MODIFICATION_SOURCE_MATERIAL_ID, Keys.FK_MODIFICATION_REQUESTER_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TModification as(String alias) {
        return new TModification(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TModification rename(String name) {
        return new TModification(name, null);
    }
}
