/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RNotificationAboutNewMaterialRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TNotificationAboutNewMaterial extends TableImpl<RNotificationAboutNewMaterialRecord> {

    /**
     * The reference instance of <code>brainshare_dev.notification_about_new_material</code>
     */
    public static final TNotificationAboutNewMaterial NOTIFICATION_ABOUT_NEW_MATERIAL = new TNotificationAboutNewMaterial();
    private static final long serialVersionUID = -1650117026;
    /**
     * The column <code>brainshare_dev.notification_about_new_material.notification_id</code>.
     */
    public final TableField<RNotificationAboutNewMaterialRecord, ULong> NOTIFICATION_ID = createField("notification_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.notification_about_new_material.reason_id</code>.
     */
    public final TableField<RNotificationAboutNewMaterialRecord, ULong> REASON_ID = createField("reason_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.notification_about_new_material</code> table reference
     */
    public TNotificationAboutNewMaterial() {
        this("notification_about_new_material", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.notification_about_new_material</code> table reference
     */
    public TNotificationAboutNewMaterial(String alias) {
        this(alias, NOTIFICATION_ABOUT_NEW_MATERIAL);
    }

    private TNotificationAboutNewMaterial(String alias, Table<RNotificationAboutNewMaterialRecord> aliased) {
        this(alias, aliased, null);
    }

    private TNotificationAboutNewMaterial(String alias, Table<RNotificationAboutNewMaterialRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RNotificationAboutNewMaterialRecord> getRecordType() {
        return RNotificationAboutNewMaterialRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RNotificationAboutNewMaterialRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATION_ABOUT_NEW_MATERIAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RNotificationAboutNewMaterialRecord>> getKeys() {
        return Arrays.<UniqueKey<RNotificationAboutNewMaterialRecord>>asList(Keys.KEY_NOTIFICATION_ABOUT_NEW_MATERIAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RNotificationAboutNewMaterialRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RNotificationAboutNewMaterialRecord, ?>>asList(Keys.FK_NOTIFICATION_ABOUT_NEW_MATERIAL_NOTIFICATION_ID, Keys.FK_NOTIFICATION_ABOUT_NEW_MATERIAL_REASON_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TNotificationAboutNewMaterial as(String alias) {
        return new TNotificationAboutNewMaterial(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TNotificationAboutNewMaterial rename(String name) {
        return new TNotificationAboutNewMaterial(name, null);
    }
}
