/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RNotificationAboutSubcommentRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TNotificationAboutSubcomment extends TableImpl<RNotificationAboutSubcommentRecord> {

    /**
     * The reference instance of <code>brainshare_dev.notification_about_subcomment</code>
     */
    public static final TNotificationAboutSubcomment NOTIFICATION_ABOUT_SUBCOMMENT = new TNotificationAboutSubcomment();
    private static final long serialVersionUID = 1001292994;
    /**
     * The column <code>brainshare_dev.notification_about_subcomment.notification_id</code>.
     */
    public final TableField<RNotificationAboutSubcommentRecord, ULong> NOTIFICATION_ID = createField("notification_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.notification_about_subcomment.reason_id</code>.
     */
    public final TableField<RNotificationAboutSubcommentRecord, ULong> REASON_ID = createField("reason_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.notification_about_subcomment</code> table reference
     */
    public TNotificationAboutSubcomment() {
        this("notification_about_subcomment", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.notification_about_subcomment</code> table reference
     */
    public TNotificationAboutSubcomment(String alias) {
        this(alias, NOTIFICATION_ABOUT_SUBCOMMENT);
    }

    private TNotificationAboutSubcomment(String alias, Table<RNotificationAboutSubcommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TNotificationAboutSubcomment(String alias, Table<RNotificationAboutSubcommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RNotificationAboutSubcommentRecord> getRecordType() {
        return RNotificationAboutSubcommentRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RNotificationAboutSubcommentRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATION_ABOUT_SUBCOMMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RNotificationAboutSubcommentRecord>> getKeys() {
        return Arrays.<UniqueKey<RNotificationAboutSubcommentRecord>>asList(Keys.KEY_NOTIFICATION_ABOUT_SUBCOMMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RNotificationAboutSubcommentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RNotificationAboutSubcommentRecord, ?>>asList(Keys.FK_NOTIFICATION_ABOUT_SUBCOMMENT_NOTIFICATION_ID, Keys.FK_NOTIFICATION_ABOUT_SUBCOMMENT_REASON_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TNotificationAboutSubcomment as(String alias) {
        return new TNotificationAboutSubcomment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TNotificationAboutSubcomment rename(String name) {
        return new TNotificationAboutSubcomment(name, null);
    }
}
