/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RNotificationAboutMaterialAchievementRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TNotificationAboutMaterialAchievement extends TableImpl<RNotificationAboutMaterialAchievementRecord> {

    /**
     * The reference instance of <code>brainshare_dev.notification_about_material_achievement</code>
     */
    public static final TNotificationAboutMaterialAchievement NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT = new TNotificationAboutMaterialAchievement();
    private static final long serialVersionUID = 42588342;
    /**
     * The column <code>brainshare_dev.notification_about_material_achievement.notification_id</code>.
     */
    public final TableField<RNotificationAboutMaterialAchievementRecord, ULong> NOTIFICATION_ID = createField("notification_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.notification_about_material_achievement.reason_id</code>.
     */
    public final TableField<RNotificationAboutMaterialAchievementRecord, ULong> REASON_ID = createField("reason_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.notification_about_material_achievement</code> table reference
     */
    public TNotificationAboutMaterialAchievement() {
        this("notification_about_material_achievement", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.notification_about_material_achievement</code> table reference
     */
    public TNotificationAboutMaterialAchievement(String alias) {
        this(alias, NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT);
    }

    private TNotificationAboutMaterialAchievement(String alias, Table<RNotificationAboutMaterialAchievementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TNotificationAboutMaterialAchievement(String alias, Table<RNotificationAboutMaterialAchievementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RNotificationAboutMaterialAchievementRecord> getRecordType() {
        return RNotificationAboutMaterialAchievementRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RNotificationAboutMaterialAchievementRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RNotificationAboutMaterialAchievementRecord>> getKeys() {
        return Arrays.<UniqueKey<RNotificationAboutMaterialAchievementRecord>>asList(Keys.KEY_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RNotificationAboutMaterialAchievementRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RNotificationAboutMaterialAchievementRecord, ?>>asList(Keys.FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_NOTIFICATION_ID, Keys.FK_NOTIFICATION_ABOUT_MATERIAL_ACHIEVEMENT_REASON_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TNotificationAboutMaterialAchievement as(String alias) {
        return new TNotificationAboutMaterialAchievement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TNotificationAboutMaterialAchievement rename(String name) {
        return new TNotificationAboutMaterialAchievement(name, null);
    }
}
