/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RObjectStorageFileRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TObjectStorageFile extends TableImpl<RObjectStorageFileRecord> {

    /**
     * The reference instance of <code>brainshare_dev.object_storage_file</code>
     */
    public static final TObjectStorageFile OBJECT_STORAGE_FILE = new TObjectStorageFile();
    private static final long serialVersionUID = 1848326210;
    /**
     * The column <code>brainshare_dev.object_storage_file.id</code>.
     */
    public final TableField<RObjectStorageFileRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.object_storage_file.bucket</code>.
     */
    public final TableField<RObjectStorageFileRecord, String> BUCKET = createField("bucket", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.object_storage_file.in_bucket_file_id</code>.
     */
    public final TableField<RObjectStorageFileRecord, String> IN_BUCKET_FILE_ID = createField("in_bucket_file_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.object_storage_file</code> table reference
     */
    public TObjectStorageFile() {
        this("object_storage_file", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.object_storage_file</code> table reference
     */
    public TObjectStorageFile(String alias) {
        this(alias, OBJECT_STORAGE_FILE);
    }

    private TObjectStorageFile(String alias, Table<RObjectStorageFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private TObjectStorageFile(String alias, Table<RObjectStorageFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RObjectStorageFileRecord> getRecordType() {
        return RObjectStorageFileRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RObjectStorageFileRecord, ULong> getIdentity() {
        return Keys.IDENTITY_OBJECT_STORAGE_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RObjectStorageFileRecord> getPrimaryKey() {
        return Keys.KEY_OBJECT_STORAGE_FILE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RObjectStorageFileRecord>> getKeys() {
        return Arrays.<UniqueKey<RObjectStorageFileRecord>>asList(Keys.KEY_OBJECT_STORAGE_FILE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TObjectStorageFile as(String alias) {
        return new TObjectStorageFile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TObjectStorageFile rename(String name) {
        return new TObjectStorageFile(name, null);
    }
}
