/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RUserDesirableSectionRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TUserDesirableSection extends TableImpl<RUserDesirableSectionRecord> {

    /**
     * The reference instance of <code>brainshare_dev.user_desirable_section</code>
     */
    public static final TUserDesirableSection USER_DESIRABLE_SECTION = new TUserDesirableSection();
    private static final long serialVersionUID = -1263890128;
    /**
     * The column <code>brainshare_dev.user_desirable_section.user_id</code>.
     */
    public final TableField<RUserDesirableSectionRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_desirable_section.section_id</code>.
     */
    public final TableField<RUserDesirableSectionRecord, UInteger> SECTION_ID = createField("section_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.user_desirable_section</code> table reference
     */
    public TUserDesirableSection() {
        this("user_desirable_section", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.user_desirable_section</code> table reference
     */
    public TUserDesirableSection(String alias) {
        this(alias, USER_DESIRABLE_SECTION);
    }

    private TUserDesirableSection(String alias, Table<RUserDesirableSectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserDesirableSection(String alias, Table<RUserDesirableSectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserDesirableSectionRecord> getRecordType() {
        return RUserDesirableSectionRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserDesirableSectionRecord> getPrimaryKey() {
        return Keys.KEY_USER_DESIRABLE_SECTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserDesirableSectionRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserDesirableSectionRecord>>asList(Keys.KEY_USER_DESIRABLE_SECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RUserDesirableSectionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RUserDesirableSectionRecord, ?>>asList(Keys.FK_USER_DESIRABLE_SECTION_USER_ID, Keys.FK_USER_DESIRABLE_SECTION_SECTION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserDesirableSection as(String alias) {
        return new TUserDesirableSection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserDesirableSection rename(String name) {
        return new TUserDesirableSection(name, null);
    }
}
