/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RUserBookmarkRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TUserBookmark extends TableImpl<RUserBookmarkRecord> {

    /**
     * The reference instance of <code>brainshare_dev.user_bookmark</code>
     */
    public static final TUserBookmark USER_BOOKMARK = new TUserBookmark();
    private static final long serialVersionUID = -915037236;
    /**
     * The column <code>brainshare_dev.user_bookmark.user_id</code>.
     */
    public final TableField<RUserBookmarkRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_bookmark.material_id</code>.
     */
    public final TableField<RUserBookmarkRecord, ULong> MATERIAL_ID = createField("material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_bookmark.bookmark_name</code>.
     */
    public final TableField<RUserBookmarkRecord, String> BOOKMARK_NAME = createField("bookmark_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_bookmark.description</code>.
     */
    public final TableField<RUserBookmarkRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");
    /**
     * The column <code>brainshare_dev.user_bookmark.material_inner_position_data</code>.
     */
    public final TableField<RUserBookmarkRecord, Object> MATERIAL_INNER_POSITION_DATA = createField("material_inner_position_data", org.jooq.impl.DefaultDataType.getDefaultDataType("json"), this, "");
    /**
     * The column <code>brainshare_dev.user_bookmark.possible_course_id</code>.
     */
    public final TableField<RUserBookmarkRecord, ULong> POSSIBLE_COURSE_ID = createField("possible_course_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * Create a <code>brainshare_dev.user_bookmark</code> table reference
     */
    public TUserBookmark() {
        this("user_bookmark", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.user_bookmark</code> table reference
     */
    public TUserBookmark(String alias) {
        this(alias, USER_BOOKMARK);
    }

    private TUserBookmark(String alias, Table<RUserBookmarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserBookmark(String alias, Table<RUserBookmarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserBookmarkRecord> getRecordType() {
        return RUserBookmarkRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserBookmarkRecord> getPrimaryKey() {
        return Keys.KEY_USER_BOOKMARK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserBookmarkRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserBookmarkRecord>>asList(Keys.KEY_USER_BOOKMARK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RUserBookmarkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RUserBookmarkRecord, ?>>asList(Keys.FK_USER_BOOKMARK_USER_ID, Keys.FK_USER_BOOKMARK_MATERIAL_ID, Keys.FK_USER_BOOKMARK_POSSIBLE_COURSE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserBookmark as(String alias) {
        return new TUserBookmark(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserBookmark rename(String name) {
        return new TUserBookmark(name, null);
    }
}
