/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RUserFavouriteMaterialRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TUserFavouriteMaterial extends TableImpl<RUserFavouriteMaterialRecord> {

    /**
     * The reference instance of <code>brainshare_dev.user_favourite_material</code>
     */
    public static final TUserFavouriteMaterial USER_FAVOURITE_MATERIAL = new TUserFavouriteMaterial();
    private static final long serialVersionUID = -1541356568;
    /**
     * The column <code>brainshare_dev.user_favourite_material.user_id</code>.
     */
    public final TableField<RUserFavouriteMaterialRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_favourite_material.material_id</code>.
     */
    public final TableField<RUserFavouriteMaterialRecord, ULong> MATERIAL_ID = createField("material_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_favourite_material.possible_course_id</code>.
     */
    public final TableField<RUserFavouriteMaterialRecord, ULong> POSSIBLE_COURSE_ID = createField("possible_course_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * Create a <code>brainshare_dev.user_favourite_material</code> table reference
     */
    public TUserFavouriteMaterial() {
        this("user_favourite_material", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.user_favourite_material</code> table reference
     */
    public TUserFavouriteMaterial(String alias) {
        this(alias, USER_FAVOURITE_MATERIAL);
    }

    private TUserFavouriteMaterial(String alias, Table<RUserFavouriteMaterialRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserFavouriteMaterial(String alias, Table<RUserFavouriteMaterialRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserFavouriteMaterialRecord> getRecordType() {
        return RUserFavouriteMaterialRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserFavouriteMaterialRecord> getPrimaryKey() {
        return Keys.KEY_USER_FAVOURITE_MATERIAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserFavouriteMaterialRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserFavouriteMaterialRecord>>asList(Keys.KEY_USER_FAVOURITE_MATERIAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RUserFavouriteMaterialRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RUserFavouriteMaterialRecord, ?>>asList(Keys.FK_USER_FAVOURITE_MATERIAL_USER_ID, Keys.FK_USER_FAVOURITE_MATERIAL_MATERIAL_ID, Keys.FK_USER_FAVOURITE_MATERIAL_POSSIBLE_COURSE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserFavouriteMaterial as(String alias) {
        return new TUserFavouriteMaterial(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserFavouriteMaterial rename(String name) {
        return new TUserFavouriteMaterial(name, null);
    }
}
