/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RUserSavedAttachmentRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TUserSavedAttachment extends TableImpl<RUserSavedAttachmentRecord> {

    /**
     * The reference instance of <code>brainshare_dev.user_saved_attachment</code>
     */
    public static final TUserSavedAttachment USER_SAVED_ATTACHMENT = new TUserSavedAttachment();
    private static final long serialVersionUID = 1043439729;
    /**
     * The column <code>brainshare_dev.user_saved_attachment.user_id</code>.
     */
    public final TableField<RUserSavedAttachmentRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_saved_attachment.attachment_object_storage_file_id</code>.
     */
    public final TableField<RUserSavedAttachmentRecord, ULong> ATTACHMENT_OBJECT_STORAGE_FILE_ID = createField("attachment_object_storage_file_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.user_saved_attachment</code> table reference
     */
    public TUserSavedAttachment() {
        this("user_saved_attachment", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.user_saved_attachment</code> table reference
     */
    public TUserSavedAttachment(String alias) {
        this(alias, USER_SAVED_ATTACHMENT);
    }

    private TUserSavedAttachment(String alias, Table<RUserSavedAttachmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserSavedAttachment(String alias, Table<RUserSavedAttachmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserSavedAttachmentRecord> getRecordType() {
        return RUserSavedAttachmentRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserSavedAttachmentRecord> getPrimaryKey() {
        return Keys.KEY_USER_SAVED_ATTACHMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserSavedAttachmentRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserSavedAttachmentRecord>>asList(Keys.KEY_USER_SAVED_ATTACHMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RUserSavedAttachmentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RUserSavedAttachmentRecord, ?>>asList(Keys.FK_USER_SAVED_ATTACHMENT_USER_ID, Keys.FK_USER_SAVED_ATTACHMENT_ATTACHMENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserSavedAttachment as(String alias) {
        return new TUserSavedAttachment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserSavedAttachment rename(String name) {
        return new TUserSavedAttachment(name, null);
    }
}
