/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;
import ua.ddovgal.brainshareApi.jooq.Keys;
import ua.ddovgal.brainshareApi.jooq.tables.records.RUserStatusInSectionRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TUserStatusInSection extends TableImpl<RUserStatusInSectionRecord> {

    /**
     * The reference instance of <code>brainshare_dev.user_status_in_section</code>
     */
    public static final TUserStatusInSection USER_STATUS_IN_SECTION = new TUserStatusInSection();
    private static final long serialVersionUID = -1898131821;
    /**
     * The column <code>brainshare_dev.user_status_in_section.user_id</code>.
     */
    public final TableField<RUserStatusInSectionRecord, ULong> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_status_in_section.section_id</code>.
     */
    public final TableField<RUserStatusInSectionRecord, UInteger> SECTION_ID = createField("section_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_status_in_section.ratio</code>.
     */
    public final TableField<RUserStatusInSectionRecord, Integer> RATIO = createField("ratio", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>brainshare_dev.user_status_in_section.status_value</code>.
     */
    public final TableField<RUserStatusInSectionRecord, String> STATUS_VALUE = createField("status_value", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>brainshare_dev.user_status_in_section</code> table reference
     */
    public TUserStatusInSection() {
        this("user_status_in_section", null);
    }

    /**
     * Create an aliased <code>brainshare_dev.user_status_in_section</code> table reference
     */
    public TUserStatusInSection(String alias) {
        this(alias, USER_STATUS_IN_SECTION);
    }

    private TUserStatusInSection(String alias, Table<RUserStatusInSectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserStatusInSection(String alias, Table<RUserStatusInSectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserStatusInSectionRecord> getRecordType() {
        return RUserStatusInSectionRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BrainshareDev.BRAINSHARE_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserStatusInSectionRecord> getPrimaryKey() {
        return Keys.KEY_USER_STATUS_IN_SECTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserStatusInSectionRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserStatusInSectionRecord>>asList(Keys.KEY_USER_STATUS_IN_SECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RUserStatusInSectionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RUserStatusInSectionRecord, ?>>asList(Keys.FK_USER_STATUS_IN_SECTION_USER_ID, Keys.FK_USER_STATUS_IN_SECTION_SECTION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserStatusInSection as(String alias) {
        return new TUserStatusInSection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserStatusInSection rename(String name) {
        return new TUserStatusInSection(name, null);
    }
}
