/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AddCommentaryMark extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>brainshare_dev.add_commentary_mark.commentary_id_param</code>.
     */
    public static final Parameter<Long> COMMENTARY_ID_PARAM = createParameter("commentary_id_param", org.jooq.impl.SQLDataType.BIGINT, false, false);
    /**
     * The parameter <code>brainshare_dev.add_commentary_mark.setter_user_id_param</code>.
     */
    public static final Parameter<Long> SETTER_USER_ID_PARAM = createParameter("setter_user_id_param", org.jooq.impl.SQLDataType.BIGINT, false, false);
    /**
     * The parameter <code>brainshare_dev.add_commentary_mark.is_up_mark_param</code>.
     */
    public static final Parameter<Byte> IS_UP_MARK_PARAM = createParameter("is_up_mark_param", org.jooq.impl.SQLDataType.TINYINT, false, false);
    private static final long serialVersionUID = 2105752128;

    /**
     * Create a new routine call instance
     */
    public AddCommentaryMark() {
        super("add_commentary_mark", BrainshareDev.BRAINSHARE_DEV);

        addInParameter(COMMENTARY_ID_PARAM);
        addInParameter(SETTER_USER_ID_PARAM);
        addInParameter(IS_UP_MARK_PARAM);
    }

    /**
     * Set the <code>commentary_id_param</code> parameter IN value to the routine
     */
    public void setCommentaryIdParam(Long value) {
        setValue(COMMENTARY_ID_PARAM, value);
    }

    /**
     * Set the <code>setter_user_id_param</code> parameter IN value to the routine
     */
    public void setSetterUserIdParam(Long value) {
        setValue(SETTER_USER_ID_PARAM, value);
    }

    /**
     * Set the <code>is_up_mark_param</code> parameter IN value to the routine
     */
    public void setIsUpMarkParam(Byte value) {
        setValue(IS_UP_MARK_PARAM, value);
    }
}
