/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MaterialStateIdFor extends AbstractRoutine<Integer> {

    /**
     * The parameter <code>brainshare_dev.material_state_id_for.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);
    /**
     * The parameter <code>brainshare_dev.material_state_id_for.material_ratio</code>.
     */
    public static final Parameter<Integer> MATERIAL_RATIO = createParameter("material_ratio", org.jooq.impl.SQLDataType.INTEGER, false, false);
    private static final long serialVersionUID = -479843287;

    /**
     * Create a new routine call instance
     */
    public MaterialStateIdFor() {
        super("material_state_id_for", BrainshareDev.BRAINSHARE_DEV, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(MATERIAL_RATIO);
    }

    /**
     * Set the <code>material_ratio</code> parameter IN value to the routine
     */
    public void setMaterialRatio(Integer value) {
        setValue(MATERIAL_RATIO, value);
    }

    /**
     * Set the <code>material_ratio</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setMaterialRatio(Field<Integer> field) {
        setField(MATERIAL_RATIO, field);
    }
}
