/*
 * This file is generated by jOOQ.
*/
package ua.ddovgal.brainshareApi.jooq.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import ua.ddovgal.brainshareApi.jooq.BrainshareDev;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RecountApprovalValue extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>brainshare_dev.recount_approval_value.material_id</code>.
     */
    public static final Parameter<Long> MATERIAL_ID = createParameter("material_id", org.jooq.impl.SQLDataType.BIGINT, false, false);
    private static final long serialVersionUID = 670260122;

    /**
     * Create a new routine call instance
     */
    public RecountApprovalValue() {
        super("recount_approval_value", BrainshareDev.BRAINSHARE_DEV);

        addInParameter(MATERIAL_ID);
    }

    /**
     * Set the <code>material_id</code> parameter IN value to the routine
     */
    public void setMaterialId(Long value) {
        setValue(MATERIAL_ID, value);
    }
}
